### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by bazo** [shadcn-ui/ui#1017]
Hi,

i am at a loss here

i have installed the cli as per the docs, configured tailwind etc...

then i installed these components button, menubar, scroll-area, separator, tabs to be able to replicate the music page example
the component files are installed fine, no errors in them

this is the code that uses them, copy pasted straight from the example, 

```tsx
import { PlusCircledIcon } from "@radix-ui/react-icons";

import { Button } from "components/ui/button";
import { ScrollArea, ScrollBar } from "components/ui/scroll-area";
import { Separator } from "components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "components/ui/tabs";

import { Menu } from "components/menu";
import { Sidebar } from "components/sidebar";

export default function RootPage() {
	return (
		<>
			<div className="md:hidden">Dake logo</div>
			<div className="hidden md:block">
				<Menu />
				<div className="border-t">
					<div className="bg-background">
						<div className="grid lg:grid-cols-5">
							<Sidebar className="hidden lg:block" />
							<div className="col-span-3 lg:col-span-4 lg:border-l">
								<div className="h-full px-4 py-6 lg:px-8">
									<Tabs defaultValue="music" className="h-full space-y-6">
										<div className="space-between flex items-center">
											<TabsList>
												<TabsTrigger value="music" className="relative">
													Music
												</TabsTrigger>
												<TabsTrigger value="podcasts">Podcasts</TabsTrigger>
												<TabsTrigger value="live" disabled>
													Live
												</TabsTrigger>
											</TabsList>
											<div className="ml-auto mr-4">
												<Button>
													<PlusCircledIcon className="mr-2 h-4 w-4" />
													Add music
												</Button>
											</div>
										</div>
										<TabsContent value="music" className="border-none p-0 outline-none">
											<div className="flex items-center justify-between">
												<div className="space-y-1">
													<h2 className="text-2xl font-semibold tracking-tight">Listen Now</h2>
													<p className="text-sm text-muted-foreground">Top picks for you. Updated daily.</p>
												</div>
											</div>
											<Separator className="my-4" />
											<div className="relative">
												<ScrollArea>
													<div className="flex space-x-4 pb-4">Tu boli albumy</div>
													<ScrollBar orientation="horizontal" />
												</ScrollArea>
											</div>
											<div className="mt-6 space-y-1">
												<h2 className="text-2xl font-semibold tracking-tight">Made for You</h2>
												<p className="text-sm text-muted-foreground">Your personal playlists. Updated daily.</p>
											</div>
											<Separator className="my-4" />
											<div className="relative">
												<ScrollArea>
													<div className="flex space-x-4 pb-4">Made for you</div>
													<ScrollBar orientation="horizontal" />
												</ScrollArea>
											</div>
										</TabsContent>
										<TabsContent value="podcasts" className="h-full flex-col border-none p-0 data-[state=active]:flex">
											<div className="flex items-center justify-between">
												<div className="space-y-1">
													<h2 className="text-2xl font-semibold tracking-tight">New Episodes</h2>
													<p className="text-sm text-muted-foreground">Your favorite podcasts. Updated daily.</p>
												</div>
											</div>
											<Separator className="my-4" />
											PodcastEmptyPlaceholder
										</TabsContent>
									</Tabs>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}

```

this is app.tsx

```tsx
import RootPage from "pages/root";

function App() {
	return <RootPage />
}

export default App;
```

but in browser i get these errors: 
```js
VM1345:1  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
eval @ VM1345:1
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useContext @ react.development.js:1602
$f631663db3294ace$export$b39126d51d94e6f3 @ Direction.tsx:22
(anonymous) @ Menubar.tsx:75
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1618  Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at useContext (react.development.js:1618:21)
    at $f631663db3294ace$export$b39126d51d94e6f3 (Direction.tsx:22:21)
    at Menubar.tsx:75:23
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)

The above error occurred in the <Menubar> component:

    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-menubar.js?v=4e6413c5:4339:11
    at _c (http://localhost:5173/src/components/ui/menubar.tsx:19:56)
    at Menu
    at div
    at RootPage
    at App
```

this is error only for menu, but tabs and scroll area also cause these errors

when i comment out the use of menu, tabs and scroll-area in sidebar, the page renders ok

am i missing something? how to fix this?

thanks

**Comment by crkos** [comment]
I see the <Menu /> in your component, is it a different component using the <Menubar> one?

Maybe you have some code in there that is causing the error

**Comment by admin-educat** [comment]
@bazo what was the issue? I'm facing the same problems. Please help!

**Comment by atng** [comment]
@bazo could you explain what was the issue? I'm having the same problems. Please help!
