### ISSUE TITLE
Failed to fetch styles from registry

### ISSUE THREAD

**Issue by MR-Khaleghi** [shadcn-ui/ui#1371]
I'm getting this error while trying to install shadcn
command: npx shadcn-ui@latest init

error:
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///C:/Users/star/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
Failed to fetch styles from registry.

**Comment by Deveesh-Shetty** [comment]
It seems more like a network issue ig, did u try installing again later?

**Comment by MR-Khaleghi** [comment]
I'm not sure it's from network.becuase there was not any network problem to open this issue on github and after 30 minutes I could install from the same network.  I guess there is some issue with shadcn.

**Comment by zf0x00** [comment]
got this issue how to solve

**Comment by Pavelsiba** [comment]
I have the same problem

PS D:\Projects\TehService> npx shadcn-ui@latest init
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: 
    at ClientRequest.<anonymous> (file:///C:/Users/OrehovPY/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: undefined
}
Failed to fetch styles from registry.

**Comment by AbbasHarati** [comment]
the same problem. I tried it with many different network on different system, but encountering the same problem!!!

**Comment by GeorgiyIakunenko** [comment]
I also have the same issuer

**Comment by radvanCZ** [comment]
The same problem for me . 

PS C:\projects\next\shadcdntest> npx shadcn-ui@latest init
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: connect ETIMEDOUT 76.76.21.123:443
    at ClientRequest.<anonymous> (file:///C:/projects/next/shadcdntest/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}
Failed to fetch styles from registry.

**Comment by GeorgiyIakunenko** [comment]
I 

> I also have the same issuer

Fixed it, problem was in http proxy certs

**Comment by radvanCZ** [comment]
I solved it ,  NPX is not using configuration for npm , so my proxy settings was  ignored  . I have to set local  user variables  in my powershell environment , that was the main  problem . 

 New-Item -Path "Env:" -Name "HTTP_PROXY" -Value "http://server:port/"
 New-Item -Path "Env:" -Name "HTTPS_PROXY" -Value "http://server:port/" 

this enabled npx to connect  shadcn repo . 

Then I have issue with untrusted certificate , I solve this by adding shadcn certificate to root certificates in certmgr.msc utility for win .

**Comment by chyun1006** [comment]
> I
> 
> > I also have the same issuer
> 
> Fixed it, problem was in http proxy certs

how do it?

**Comment by onemahmoudadel** [comment]
New-Item -Path 'Env:' -Name 'HTTP_PROXY' -Value 'https://ui.shadcn.com/'

I encountered the same problem, tried your solution and the problem was fixed. Thank you


> I solved it. NPX does not use the npm configuration, so my proxy settings were ignored. I had to set local user variables in my PowerShell environment, which was the main problem.
> 
> To resolve this, I used the following commands in PowerShell:
> 
> New-Item -Path 'Env:' -Name 'HTTP_PROXY' -Value 'http://server:port/' New-Item -Path 'Env:' -Name 'HTTPS_PROXY' -Value 'http://server:port/' This enabled NPX to connect to the shadcn repository.
> 
> Then, I encountered an issue with an untrusted certificate. I resolved this by adding the shadcn certificate to the root certificates in the certmgr.msc utility for Windows.

**Comment by alipalvane** [comment]
Your region is probably blocked by shadcn. I also had this problem and changed the proxy and was able to install it. If you use a proxy, test different regions.

**Comment by RowdyKGZ** [comment]
> I have the same problem
> 
> PS D:\Projects\TehService> npx shadcn-ui@latest init FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: at ClientRequest. (file:///C:/Users/OrehovPY/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11) at ClientRequest.emit (node:events:514:28) at TLSSocket.socketErrorListener (node:_http_client:495:9) at TLSSocket.emit (node:events:514:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: undefined } Failed to fetch styles from registry.

really helped!!!

**Comment by RowdyKGZ** [comment]
> I solved it. NPX does not use the npm configuration, so my proxy settings were ignored. I had to set local user variables in my PowerShell environment, which was the main problem.
> 
> To resolve this, I used the following commands in PowerShell:
> 
> New-Item -Path 'Env:' -Name 'HTTP_PROXY' -Value 'http://server:port/' New-Item -Path 'Env:' -Name 'HTTPS_PROXY' -Value 'http://server:port/' This enabled NPX to connect to the shadcn repository.
> 
> Then, I encountered an issue with an untrusted certificate. I resolved this by adding the shadcn certificate to the root certificates in the certmgr.msc utility for Windows.

really helped

**Comment by ariannargesi** [comment]
I had this issue in VSCodes terminal. 
If you are lazy and you don't want to get involved with proxy stuff, you can type the command in your OS terminal instead of VSCode.

Worked for me :)

**Comment by BroJenuel** [comment]
I dont know if this issue same as mine,,, I installed the chadcdn, everything is fine but I am having this error.. my lib folder does not have registry folder.
![image](https://github.com/shadcn-ui/ui/assets/31676163/a137bec5-710f-4edb-91f2-8b3c77cf10d7)

**Comment by Josh-Savvy** [comment]
> I solved it. NPX does not use the npm configuration, so my proxy settings were ignored. I had to set local user variables in my PowerShell environment, which was the main problem.
> 
> To resolve this, I used the following commands in PowerShell:
> 
> New-Item -Path 'Env:' -Name 'HTTP_PROXY' -Value 'http://server:port/' New-Item -Path 'Env:' -Name 'HTTPS_PROXY' -Value 'http://server:port/' This enabled NPX to connect to the shadcn repository.
> 
> Then, I encountered an issue with an untrusted certificate. I resolved this by adding the shadcn certificate to the root certificates in the certmgr.msc utility for Windows.

Hello there.
I'm having this same issue on Mac. Do you have any idea how I could fix this on Mac?

**Comment by anujgupta5686** [comment]
I am also facing the same error. How to fixed this issue? 
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: connect ETIMEDOUT 76.76.21.164:443
    at ClientRequest.<anonymous> (file:///C:/Users/anujk/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:526:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}
Failed to fetch styles from registry.

**Comment by wuqianrui** [comment]
My operating environment is Windows. I used Google to look up the IP address for `https://www.shadcn-vue.com/registry/styles/index.json` and found it to be `104.21.17.226` . and  I edited the hosts file on my Windows computer, adding the line:
```text
104.21.17.226 www.shadcn-vue.com
```
With this addition, the configuration takes effect locally for me; however, some Windows devices might require a restart for the changes in the hosts file to be applied.

Side note: As a Chinese person, dealing with these sorts of network issues can often be quite draining.

Hope you can  enjoy it !!!

**Comment by Shazzad998** [comment]
I encountered a similar issue where I couldn't even access the shadcn website. I set my region settings to the correct location, and the problem was resolved. Previously it was set to the United States

**Comment by deepakA18** [comment]
I encountered the same issue in NextJS 14 version, And resolved it by opening a new terminal and again running the command:
npx shadcn-ui@latest init  in a new terminal and it worked!

**Comment by AllThingsSmitty** [comment]
I'm encountering the exact same thing running `npx shadcn-ui@latest init`:

```
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///C:/Users/c8m9s/AppData/Local/npm-cache/_npx/2c1ae577c581653c/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:492:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
```

I tried the Powershell proxy update suggested above:

```
New-Item -Path 'Env:' -Name 'HTTP_PROXY' -Value 'http://localhost:3000/'
New-Item -Path 'Env:' -Name 'HTTPS_PROXY' -Value 'http://localhost:3000/'
```

This didn't resolve the issue.

**Comment by Falasefemi2** [comment]
i am having the same issue currently how do i go about it?
npx shadcn-ui@latest add card
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///C:/Users/HP/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
Failed to fetch components from registry.

**Comment by deepakA18** [comment]
@Falasefemi2 
Try by killing the terminal and open the new terminal and enter the command again!
Don't know how but, this worked for me twice

**Comment by Vikashrock45** [comment]
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: write EPROTO 00E6541201000000:error:0A00010B:SSL routines:tls_validate_record_header:wrong version number:ssl/record/methods/tlsany_meth.c:81:

    at ClientRequest.<anonymous> (file:///Users/vikash/Desktop/bloggr/frontend/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO',
  erroredSysCall: 'write'
}
Failed to fetch components from registry.
getting this error on my mac.

**Comment by youwei997** [comment]
Add the following two lines to the Windows hosts file and restart your computer
```
104.21.17.226 www.shadcn-vue.com
76.76.21.9 www.ui.shadcn.com
```

**Comment by mayasingh5** [comment]
this is because the network you are using has blocked shadcn. I was using my company network. Got this issue, realized then.

**Comment by ayomide-yoke** [comment]
> I solved it. NPX does not use the npm configuration, so my proxy settings were ignored. I had to set local user variables in my PowerShell environment, which was the main problem.
> 
> To resolve this, I used the following commands in PowerShell:
> 
> New-Item -Path 'Env:' -Name 'HTTP_PROXY' -Value 'http://server:port/' New-Item -Path 'Env:' -Name 'HTTPS_PROXY' -Value 'http://server:port/' This enabled NPX to connect to the shadcn repository.
> 
> Then, I encountered an issue with an untrusted certificate. I resolved this by adding the shadcn certificate to the root certificates in the certmgr.msc utility for Windows.

Thank you for your answer. Please can you provide any information about how you add shadcn certificate to the certmgr.msc utility

**Comment by Samiha13** [comment]
How to solve this issue ?

npm error code ERR_INVALID_URL
npm error Invalid URL
npm error A complete log of this run can be found in: C:\Users\USER\AppData\Local\npm-cache\_logs\2024-07-01T19_59_18_590Z-debug-0.log

**Comment by Samiha13** [comment]
Use a VPN while installing shadcn ui .

**Comment by mahima98** [comment]
I deleted my **'node modules'** folder, 
**pnpm install it** again 
and finally run the command: **npx shadcn-vue@latest init** 
it worked for me !

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by azamat-cto** [comment]
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

request to https://ui.shadcn.com/r/styles/index.json failed, reason: unable to verify the first certificate

I'm getting this error

**Comment by Gbadebo-Oluwarimi** [comment]
Encountered this issue today while trying to install the carousel component and found out that this error is due to an untrusted certificate in PowerShell while using shadcn, you can bypass the certificate validation check
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }`

this just a temporarily disables validation check for your session 
Hope it work for you guys

**Comment by deemeetree** [comment]
I'm having the same issue when trying to deploy my v0 project

**Comment by Asinging** [comment]
> npx shadcn-ui@latest init

This works for me!
