### ISSUE TITLE
Error while installing , TypeError: Cannot redefine property: File

### ISSUE THREAD

**Issue by saketverma-03** [shadcn-ui/ui#1470]
``` 

    ~/code/ecom  npx shadcn-ui@latest init                                                                                                127 ✘ 
/home/saket/.npm/_npx/125ee17d583c4e03/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/home/saket/.npm/_npx/125ee17d583c4e03/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/saket/.npm/_npx/125ee17d583c4e03/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.6.0
```
im getting this error im trying to install it in an next app following this  [page link](https://ui.shadcn.com/docs/installation/next)

i tried installing it using npx yarn pnpm and bunx .
node version v20.6.0 installed using nvm
OS: manjaro linux

**Comment by Bonchouuuur** [comment]
The reason is your Node version, enforce it to 20.5.1 then you'll be able to go

See https://github.com/shadcn-ui/ui/issues/1458 for more details

**Comment by ezeparziale** [comment]
I downgraded to 20.5.1, https://nodejs.org/download/release/v20.5.1/ and works fine

**Comment by saketverma-03** [comment]
downgrading to v20.5.1 worked .
