### ISSUE TITLE
bunx shadcn-ui@latest init

### ISSUE THREAD

**Issue by patbhakta** [shadcn-ui/ui#1496]
file:///tmp/shadcn-ui@latest--bunx/node_modules/shadcn-ui/dist/index.js:67
      `Failed to load tsconfig.json. ${tsConfig.message ?? ""}`.trim()
                                                         ^
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error: "shadcn-ui" exited with code 1 (SIGHUP)

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.
