### ISSUE TITLE
Failed to tetch components from registry.How to fix it?

### ISSUE THREAD

**Issue by Mecil9** [shadcn-ui/ui#1671]
pnpm dlx shadcn-ui@latest add select

Packages: +198
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 198, reused 198, downloaded 0, added 198, done
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///Users/mecilmeng/Library/pnpm/store/v3/tmp/dlx-41132/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
Failed to fetch components from registry.

**Comment by Mecil9** [comment]
I change to other way to add select component
npx shadcn-ui@latest add select
same issue.
```code
Need to install the following packages:
shadcn-ui@0.4.1
Ok to proceed? (y) y
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///Users/mecilmeng/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
Failed to fetch components from registry.
```

**Comment by malikkotb** [comment]
I have the same issue:
```pnpm dlx shadcn-ui@latest add popover

Packages: +199
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 199, reused 199, downloaded 0, added 199, done
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///Users/.../Library/pnpm/store/v3/tmp/dlx-86635/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
Failed to fetch components from registry.```

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.
