### ISSUE TITLE
Error with React Context Creation in @radix-ui/react-dismissable-layer

### ISSUE THREAD

**Issue by thewbuk** [shadcn-ui/ui#2041]
I'm encountering a runtime error in my Next.js application involving the @radix-ui/react-dismissable-layer package. The application fails with the following error message:

`Error: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function`

Code :
```

                        <Dialog>
                          <DialogTrigger asChild>
                            <Button size="sm" className="relative" disabled>
                              Add channel
                            </Button>
                          </DialogTrigger>
                          <DialogContent>
                            <DialogHeader>
                              <DialogTitle>Add Podcast</DialogTitle>
                              <DialogDescription>
                                Copy and paste the podcast feed URL to import.
                              </DialogDescription>
                            </DialogHeader>
                            <div className="grid gap-4 py-4">
                              <div className="grid gap-2">
                                <Label>Podcast URL</Label>
                                <Input
                                  id="url"
                                  placeholder="https://example.com/feed.xml"
                                />
                              </div>
                            </div>
                            <DialogFooter>
                              <Button>Import Podcast</Button>
                            </DialogFooter>
                          </DialogContent>
                        </Dialog>
```

Full error message:

```
Server Error

Error: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
eval
node_modules\@radix-ui\react-dismissable-layer\dist\index.mjs (23:89)
(rsc)/./node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs
```

`    "@radix-ui/react-dismissable-layer": "^1.0.5",`

**Comment by pratik2e** [comment]
Error: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function

code:
`import React from 'react'
import { Name } from '../comp/name.js'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const Page = () => {
  return (
    <div className='text-center my-2'>
    <div>
    <Name/>
    </div>
    <h2 className='my-4'>Menu</h2>
    <Accordion type="single" collapsible>
  <AccordionItem value="item-1">
    <AccordionTrigger>Is it accessible?</AccordionTrigger>
    <AccordionContent>
      Yes. It adheres to the WAI-ARIA design pattern.
    </AccordionContent>
  </AccordionItem>
</Accordion>

    </div>
  )
}

export default Page`

full error message:
`⨯ node_modules\.pnpm\@radix-ui+react-context@1.0.1_react@18.2.0\node_modules\@radix-ui\react-context\dist\index.mjs (34:63) @ defaultContext     
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at $c512c27ab02ef895$export$fd42f52fd3ae1109 (webpack-internal:///(rsc)/./node_modules/.pnpm/@radix-ui+react-context@1.0.1_react@18.2.0/node_modules/@radix-ui/react-context/dist/index.mjs:37:95)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@radix-ui+react-collapsible@1.0.3_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/react-collapsible/dist/index.mjs:35:98)
    at (rsc)/./node_modules/.pnpm/@radix-ui+react-collapsible@1.0.3_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/react-collapsible/dist/index.mjs (D:\next-react-astro-svelte\restra\.next\server\vendor-chunks\@radix-ui+react-collapsible@1.0.3_react-dom@18.2.0_react@18.2.0.js:20:1)    
    at __webpack_require__ (D:\next-react-astro-svelte\restra\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@radix-ui+react-accordion@1.1.2_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/react-accordion/dist/index.mjs:23:85)
    at (rsc)/./node_modules/.pnpm/@radix-ui+react-accordion@1.1.2_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/react-accordion/dist/index.mjs (D:\next-react-astro-svelte\restra\.next\server\vendor-chunks\@radix-ui+react-accordion@1.1.2_react-dom@18.2.0_react@18.2.0.js:20:1)
    at __webpack_require__ (D:\next-react-astro-svelte\restra\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/components/ui/accordion.jsx:12:83)
    at (rsc)/./src/components/ui/accordion.jsx (D:\next-react-astro-svelte\restra\.next\server\app\page.js:173:1)
    at __webpack_require__ (D:\next-react-astro-svelte\restra\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.js:10:82)
    at (rsc)/./src/app/page.js (D:\next-react-astro-svelte\restra\.next\server\app\page.js:151:1)
    at Function.__webpack_require__ (D:\next-react-astro-svelte\restra\.next\server\webpack-runtime.js:33:42)
    at async eq (D:\next-react-astro-svelte\restra\node_modules\.pnpm\next@14.0.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:401319)
    at async tr (D:\next-react-astro-svelte\restra\node_modules\.pnpm\next@14.0.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405046)
    at async tn (D:\next-react-astro-svelte\restra\node_modules\.pnpm\next@14.0.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405596)
    at async tn (D:\next-react-astro-svelte\restra\node_modules\.pnpm\next@14.0.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405727)
    at async tu (D:\next-react-astro-svelte\restra\node_modules\.pnpm\next@14.0.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:409938)
    at async D:\next-react-astro-svelte\restra\node_modules\.pnpm\next@14.0.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:410457 {
  digest: '1831627439',
  page: '/'
}
null
`

nothing working give me some solutions

**Comment by rajput-hemant** [comment]
@thewbuk 

The reason for the error is that the Radix primitives for the dialog component utilize hooks but lack the necessary `useClient` directives at the top of the file. Consequently, when using the dialog in server components, this results in the mentioned error.

However, if you are implementing the dialog in a client component, it should work seamlessly.
It's worth noting that for consistent styling, it is advisable to opt for shadcn/ui components instead of Radix primitives.

**Comment by indigoscipio** [comment]
> Try adding `"use client"` to the top of each shadcn component file.

thanks mate it work

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.
