### ISSUE TITLE
node:fs:603   handleErrorFromBinding(ctx);

### ISSUE THREAD

**Issue by pratham5368** [shadcn-ui/ui#2084]
npx shadcn-ui@latest init
node:fs:603
  handleErrorFromBinding(ctx);
  ^

Error: package.json: ENOENT: no such file or directory, open 'package.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (C:\Users\prath\AppData\Local\npm-cache\_npx\125ee17d583c4e03\node_modules\jsonfile\index.js:50:22)
    at Te (file:///C:/Users/prath/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:124:3741)
    at xt (file:///C:/Users/prath/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:124:3872)
    at file:///C:/Users/prath/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:124:4099
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'package.json'
}

**Comment by Erfan-Asadi** [comment]
I used: `npm cache clean --force` to clear npm cache and then,
try again: `npx shadcn/ui@latest add` and worked for me.

**Comment by Erfan-Asadi** [comment]
I got same error when try to installing compnents by this code: `npx shadcn-ui@latest add`.
but used: `npm cache clean --force` to clear npm cache and then,
try again: `npx shadcn-ui@latest add` and worked for me.

**Comment by ktomascz** [comment]
Make sure you are in the project's folder, when running the command (and that the project has been initialized). 
Seems like it can't find the 'package.json' file.

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.
