### ISSUE TITLE
npx shadcn-ui@latest init

### ISSUE THREAD

**Issue by marksikaundi** [shadcn-ui/ui#2122]
Can someone help me with this error am getting when i run the command
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/marksikaundi/.npm/_npx/125ee17d583c4e03/node_modules/zod/lib/index.mjs' imported from /Users/marksikaundi/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js
Did you mean to import zod/lib/index.js?
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.17.1
marksikaundi@MacBook-Air lupleg-website % npx shadcn-ui@latest init

**Comment by Aladdin4u** [comment]
I'm having the same issue

**Comment by anilmenawat** [comment]
I am having the similar issue. The error is about using useEffect in a server component in /react/primitive/src/Primitive.tsx.

**Comment by jdavmo** [comment]
I had the same problem here, I was using Nodejs v20.10.0 and after switching to Nodejs v18.19.0 everything worked fine.

**Comment by shadcn** [comment]
Can you check which `zod` version is being installed?

**Comment by nahuepera5** [comment]
Hello, i have the same issue.
Did you find any solution?

**Comment by nahuepera5** [comment]
> Hello, i have the same issue. Did you find any solution?

Hey, finally, my problem was that I was using node 14.
I updated it to node 21 and it works

**Comment by marksikaundi** [comment]
> > Hello, I have the same issue. Did you find any solution?
> 
> Hey, finally, my problem was that I was using node 14.
> I updated it to node 21 and it works

It's good you managed to solve it

**Comment by kgcarroll** [comment]
Anyone reading this in 2024... check your node version. 🤙

**Comment by artsiders** [comment]
I have the same error and I am using the latest version of nodejs "v20.11.0"
please how can i do to solve that ?

**Comment by Damola180** [comment]
> I had the same problem here, I was using Nodejs v20.10.0 and after switching to Nodejs v18.19.0 everything worked fine.

how were able to switch from v20 to v18

**Comment by marksikaundi** [comment]
> > I had the same problem here, I was using Nodejs v20.10.0 and after switching to Nodejs v18.19.0 everything worked fine.
> 
> how were able to switch from v20 to v18

You can use NVM

**Comment by TanzimHossain2** [comment]
> Try this command `npx shadcn-ui init` It worked for me

Thank bro It work's . but npx shadcn-ui@latest init
  not working 😂

**Comment by marksikaundi** [comment]
> > Try this command `npx shadcn-ui init` It worked for me
> 
> Thank bro It work's . but npx shadcn-ui@latest init not working 😂

Also try to use NODEJS v18 LTS, works perfect.

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by iamkashifkhn** [comment]
I am working on a project which i using node.js 14 and i am facing this error now. I dont want to change my node.js version as we have many dependencies on it.

npx: installed 171 in 87.257s
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:43:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:257:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:58:21)
    at async Promise.all (index 11)
    at async link (internal/modules/esm/module_job.js:63:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}

**Comment by marksikaundi** [comment]
> I am working on a project which i using node.js 14 and i am facing this error now. I dont want to change my node.js version as we have many dependencies on it.
> 
> npx: installed 171 in 87.257s internal/process/esm_loader.js:74 internalBinding('errors').triggerUncaughtException( ^
> 
> Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11) at new ModuleJob (internal/modules/esm/module_job.js:43:26) at Loader.getModuleJob (internal/modules/esm/loader.js:257:11) at async ModuleWrap. (internal/modules/esm/module_job.js:58:21) at async Promise.all (index 11) at async link (internal/modules/esm/module_job.js:63:9) { code: 'ERR_UNKNOWN_BUILTIN_MODULE' }

You need nodejs V18 above

**Comment by farajabien** [comment]
I found that this issue is largely related to the version of `shadcn-ui` you're using. I encountered the same error when trying to work with the `radio-group` component.

To resolve the issue, you'll need to uninstall `shadcn-ui` and reinitialize it. Here's how:

1. Uninstall the old version:
   ```bash
   npm uninstall -g npx shadcn-ui
   ```

2. Remove the existing `components.json` file:
   ```bash
   rm components.json
   ```

3. Reinitialize `shadcn-ui`:
   ```bash
   npx shadcn@latest init
   ```

4. Follow the initialization process as prompted.

5. After reinitializing, you can add components like this:
   ```bash
   npx shadcn@latest add radio-group
   ```

---
This should help you get past the issue.

**Comment by virtueDe** [comment]
I'm also having this issue, my node version is 18.20.0.
'npx shadcn init' can be allowed

**Comment by TanzimHossain2** [comment]
@virtueDe Has your issue been resolved?

**Comment by marksikaundi** [comment]
> ~Can you check which `zod` version is being installed?~
> 
> My bad (`zod` is in cli). I'll check it out.

Has this been fixed @shadcn ?
