### ISSUE TITLE
Failed to fetch tree from registry while using npx shadcn-ui@latest add 

### ISSUE THREAD

**Issue by udaya28** [shadcn-ui/ui#2188]
I am getting the following error while using npx shadcn-ui@latest add {component name} or using shadcn-ui CLI
can someone help me, stuck for a while ?

```
 npx shadcn-ui@latest add table
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///home/udaya/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/body.js:150:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/udaya/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4266
    at async Promise.all (index 0)
    at async j (file:///home/udaya/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4233)
    at async D (file:///home/udaya/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:3956)
    at async Command.<anonymous> (file:///home/udaya/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:3:1965)

Failed to fetch tree from registry.

``` 
**with little bit of debugging found that content returned form the API is '404 html page'**

## Tried following but did't work
1. change the network and use vpn
2. Update npm and node
3. Clear npm Cache
4. shadcn-ui CLI

### Project config
1. nextjs v14.0.4
2. node v20.10.0
3. npx v10.2.5
5. shadcn-ui CLI v0.1.0

I can provide more details if needed

**Comment by udaya28** [comment]
sorry my bad while editing `components.json` file I accidentally changes style filed to empty string
I changed back to "default" it started working    


![image](https://github.com/shadcn-ui/ui/assets/54870625/5870870e-b4fe-49b5-9f15-9f3c33d1f04b)

**Comment by kmasalam** [comment]
I am also getting the same error. 
 the error code is
 
 npx shadcn-ui@latest add popover
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4419
    at async Promise.all (index 0)
    at async N (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4386)
    at async S (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:3644)
    at async Command.<anonymous> (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:3:1986)
    
 

    
    my components.json is like this
    
    {
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "",
    "cssVariables": false,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}

**Comment by udaya28** [comment]
not sure  @kmasalam , 
 if you need help you can re-open the issue tagging maintainers

**Comment by Miten15** [comment]
@kmasalam try initializes the shadcn-ui configuration in your project, by using "npx shadcn-ui@latest init" it might fixed it, i was also facing the some issue.

**Comment by Pieter1821** [comment]
i  deleted the components/ui folder, that disrupted the expected structure. Reinitializing the shadcn/ui configuration with npx shadcn-ui@latest init restores the necessary setup, and resolved the issue for me

**Comment by ianscott313** [comment]
I also ran into this. I found the issue was due to a mismatch in `components.json` between my v0 project and the target project I was adding the block to.

v0 components.json:
```
 ...
  "style": "default",
  "tailwind": {
    ...
    "baseColor": "neutral",
  }
```

target project components.json:
```
 ...
  "style": "new-york",
  "tailwind": {
    ...
    "baseColor": "zinc",
  }
```

after changing my target-project to match the v0's style and baseColor in components.json, the issue resolved.
