### ISSUE TITLE
Getting mismatch from server/client on resizable component

### ISSUE THREAD

**Issue by danielx-art** [shadcn-ui/ui#2255]
I did the manual installation to use the new Resizable component of Shadcn on an already existing project.
I'm using Next13 but not using the app directory/server components. 
Copied the demo of Resizable from the website and I'm getting this Warning, not sure what to do:

client.js:2 Warning: Prop `data-panel-size` did not match. Server: "null" Client: "50.0"
    at div
    at PanelWithForwardedRef (webpack-internal:///./node_modules/react-resizable-panels/dist/react-resizable-panels.browser.development.esm.js:60:3)
    at forwardRef(Panel)
    at div
    at PanelGroupWithForwardedRef (webpack-internal:///./node_modules/react-resizable-panels/dist/react-resizable-panels.browser.development.esm.js:1157:3)
    at forwardRef(PanelGroup)
    at ResizablePanelGroup (webpack-internal:///./src/components/micro/Resizable.tsx:17:11)

**Comment by simon-v-swyftx** [comment]
What version did you install?
Shadcn uses [0.0.55](https://github.com/shadcn-ui/ui/blob/main/apps/www/package.json#L72) of `react-resizable-panels`

**Comment by arnau01** [comment]
ty help me solve similar issue!

**Comment by tifandotme** [comment]
> What version did you install? Shadcn uses [0.0.55](https://github.com/shadcn-ui/ui/blob/main/apps/www/package.json#L72) of `react-resizable-panels`

Why did shadcn/ui use an old version though?

**Comment by danielx-art** [comment]
I installed the last version as orientations in the shadcn/docs. I reverted back to no not use shadcn, do not have it anymore.

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.
