### ISSUE TITLE
error when installing shadcn

### ISSUE THREAD

**Issue by yooosef3** [shadcn-ui/ui#2280]
hi
anyone knows whats the error reason when I try to install shadcn using npx shadcn-ui@latest init or npx shadcn-ui init

this error:

PS D:\projects\lawyer-appointment> npx shadcn-ui init
Need to install the following packages:
  shadcn-ui
Ok to proceed? (y) y
node:fs:581
  return binding.open(
                 ^

Error: package.json: ENOENT: no such file or directory, open 'D:\projects\lawyer-appointment\package.json'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at Object.readFileSync (C:\Users\hp\AppData\Local\npm-cache\_npx\74755fd285ad77f7\node_modules\jsonfile\index.js:50:22)
    at Ae (file:///C:/Users/hp/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:245:4075)
    at zt (file:///C:/Users/hp/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:245:4206)
    at file:///C:/Users/hp/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:245:4433
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)       
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) { 
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\projects\\lawyer-appointment\\package.json'
}

Node.js v20.10.0
![Capture](https://github.com/shadcn-ui/ui/assets/95876059/3349ef0f-b371-4789-9cf1-dcfbddcac230)

**Comment by rishabhbizzle** [comment]
can you share the code of your package.json file?

**Comment by d-tietjen** [comment]
Hi, the same issue just happened to me. Here is the `package.json` code:

```
{
  "name": "test-site",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.0.4"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "eslint": "^8",
    "eslint-config-next": "14.0.4"
  }
}

```

**Comment by Piyush-Kumar-Ghosh** [comment]
Hey there! It seems like you're encountering an issue while trying to install shadcn-ui. The error indicates that it's unable to find the 'package.json' file in your 'D:\projects\lawyer-appointment' directory.

To resolve this:
1. Ensure you are running the command in the root directory of your project.
2. Confirm that a 'package.json' file exists in the specified directory.

If the issue persists, you might want to:
1. Double-check the correctness of your project structure.
2. Run the command in a newly created directory with a 'package.json'.

Share more details if the problem persists.

**Comment by demczenko** [comment]
![image](https://github.com/shadcn-ui/ui/assets/134509169/5c2ad553-8514-4b9e-a134-c8f4e4f5dda7)

Check this one.
https://stackoverflow.com/questions/51819180/i-keep-getting-errno-4058-from-npm

**Comment by suhailkassar11** [comment]
I think You are in the wrong directory. you are not in the same directory where the node module or package.json is installed

**Comment by yooosef3** [comment]
> can you share the code of your package.json file?

{
  "name": "lawyer",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "13.5.6",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10",
    "postcss": "^8",
    "tailwindcss": "^3",
    "typescript": "^5"
  },
  "description": "This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).",
  "main": "next.config.js",
  "keywords": [],
  "author": "",
  "license": "ISC"
}

**Comment by yooosef3** [comment]
now i got this error
![Uploading Capture.PNG…]()

**Comment by suhailkassar11** [comment]
your png file is not uploaded please reupload

**Comment by Sudarsh1010** [comment]
did you try. `rm -rf node_modules package-lock.json && npm i && npx shadcn-ui@latest init`

**Comment by adikal25** [comment]
try changing directory from the parent directory to child directory. (cd **nameofyourprojectyoucreated**)

**Comment by aniketicloud** [comment]
I am getting the same error for new Remix project. I cleared cache (C:/Users/usernameAppData/Local/npm-cache/_npx).
I get this error on Node 20. 
Steps to reproduce:
1- npx create-remix@latest my-app
2- npx shadcn-ui@latest init

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by twillard22** [comment]
None of these solved my problem. I had to run `npm install -g pnpm` in order for `@latest` (and without `@latest`) to work. It seems the scripts now require you to have `pnpm` installed if using `npx` (I haven't tested any others).

**Comment by MrEshunOfficial** [comment]
i keep having the same problem. ive followed in guided steps provided by chat gpt, claude, etc. that still not fixing the problem. what going on?

**Comment by twillard22** [comment]
@MrEshunOfficial have you tried what I suggested?

**Comment by emmasuarezz** [comment]
> None of these solved my problem. I had to run `npm install -g pnpm` in order for `@latest` (and without `@latest`) to work. It seems the scripts now require you to have `pnpm` installed if using `npx` (I haven't tested any others).

It totally worked for me! Thanks

**Comment by SageIago** [comment]
This is what mine is showing 

node:internal/modules/esm/resolve:214
  const resolvedOption = FSLegacyMainResolve(packageJsonUrlString, packageConfig.main, baseStringified);
                         ^

Error: Cannot find package 'C:\Users\HP\AppData\Local\npm-cache\_npx\d66c5096c7023bfb\node_modules\wcwidth\package.json' imported from C:\Users\HP\AppData\Local\npm-cache\_npx\d66c5096c7023bfb\node_modules\ora\index.js
    at legacyMainResolve (node:internal/modules/esm/resolve:214:26)
    at packageResolve (node:internal/modules/esm/resolve:832:14)
    at moduleResolve (node:internal/modules/esm/resolve:918:18)
    at defaultResolve (node:internal/modules/esm/resolve:1148:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v21.7.1

**Comment by Ronit-gurjar** [comment]
> This is what mine is showing 
> 
> node:internal/modules/esm/resolve:214
>   const resolvedOption = FSLegacyMainResolve(packageJsonUrlString, packageConfig.main, baseStringified);
>                          ^
> 
> Error: Cannot find package 'C:\Users\HP\AppData\Local\npm-cache\_npx\d66c5096c7023bfb\node_modules\wcwidth\package.json' imported from C:\Users\HP\AppData\Local\npm-cache\_npx\d66c5096c7023bfb\node_modules\ora\index.js
>     at legacyMainResolve (node:internal/modules/esm/resolve:214:26)
>     at packageResolve (node:internal/modules/esm/resolve:832:14)
>     at moduleResolve (node:internal/modules/esm/resolve:918:18)
>     at defaultResolve (node:internal/modules/esm/resolve:1148:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
>     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
>     at link (node:internal/modules/esm/module_job:86:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> 
> Node.js v21.7.1

I am getting similar error when trying to install ShadCN component from cli...I have tried deleting npm cache, even reinstalling node, but the error is persistent. 

@shadcn can you reopen this issue

**Comment by shadcn** [comment]
@Ronit-gurjar let's open a new thread since we have a new cli. thank you.

**Comment by RogerioGT** [comment]
> my pro

I am attempting to do it this way, but no luck. 
How exactly did you enter the code? 
Thanks!

**Comment by uvislive** [comment]
![image](https://github.com/user-attachments/assets/afd230f9-8c29-49af-8ee6-162973703a39)
got this error when i am trying to use select component with the typescript ? i dont know how to resolve this issue

**Comment by Ronit-gurjar** [comment]
> ![image](https://github.com/user-attachments/assets/afd230f9-8c29-49af-8ee6-162973703a39)
> got this error when i am trying to use select component with the typescript ? i dont know how to resolve this issue

Try this command in terminal:

`npm install @radix-ui/react-select
`
Or go to ShadCN select docs and install manually

**Comment by sabawoonsediq** [comment]
The same error occurred in my computer 😞, can you please solve the problem @shadcn.

**Comment by sabawoonsediq** [comment]
@yooosef3 bro, how did you solve the issue, can you please explain it to me?

**Comment by rohhann12** [comment]
@shadcn can you solve this?

**Comment by uvislive** [comment]
Already installed it but still  Not working , still showing me that issue

**Comment by kwesisam** [comment]
npx shadcn@latest init
'shadcn' is not recognized as an internal or external command,
operable program or batch file.

**Comment by muhammvd** [comment]
@kwesisam I am facing the same issue were you able to solve it?

**Comment by ceeblacaliciise** [comment]
how to sole these error v
