### ISSUE TITLE
Cannot find module '@ts-morph/common'

### ISSUE THREAD

**Issue by ziddkh** [shadcn-ui/ui#2384]
Got an error while init shadcn/ui, this happen when I create new next js app and want installing shadcn/ui.
Please help me to fix this

Here's the error that i got

```bash
node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module '@ts-morph/common'
Require stack:
- C:\Users\user123\AppData\Local\npm-cache\_npx\125ee17d583c4e03\node_modules\ts-morph\dist\ts-morph.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\user123\AppData\Local\npm-cache\_npx\125ee17d583c4e03\node_modules\ts-morph\dist\ts-morph.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user123\\AppData\\Local\\npm-cache\\_npx\\125ee17d583c4e03\\node_modules\\ts-morph\\dist\\ts-morph.js'
  ]
}

Node.js v20.11.0
```

Regards,
Zidd

**Comment by mauriciomutte** [comment]
I had the same error. Using the latest version `npx shadcn-ui@0.6.0 init` works fine for me

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by avhn** [comment]
At `C:\Users\user123\AppData\Local\npm-cache` the dependency's resolved as not found. 
Remove the npm-cache at that location and do `npm install` at project root, it will work.

**Comment by INGENIO-237** [comment]
> At `C:\Users\user123\AppData\Local\npm-cache` the dependency's resolved as not found. Remove the npm-cache at that location and do `npm install` at project root, it will work.

Have tried this solution on Ubuntu but doesn't work.

![Screenshot from 2024-04-24 12-38-40](https://github.com/shadcn-ui/ui/assets/75552331/8411fccb-3a21-4a95-8c18-179cb53ad31b)

**Comment by ch1298abhishek** [comment]
did you find any solution for this??

**Comment by INGENIO-237** [comment]
> did you find any solution for this??

Yeah I did. Just tried the solution suggested by @mauriciomutte. When using `npx shadcn-ui@latest ....` it was using version `0.2.x` of shadcn-ui. So what I did was uninstalling the package and explicitly use `npx shadcn-ui@0.6.0 add ...`. And it worked.

**Comment by ivanpk938** [comment]
removing all files in .**npm** directory resolved the problem for me

**Comment by jacquelineleone** [comment]
> I had the same error. Using the latest version `npx shadcn-ui@0.6.0 init` works fine for me

This works for me! Thank you!

**Comment by Tiam-Rietsch** [comment]
Hello I am having the same issue 
I am trying to install shadcn from wsl in windows 

1. I started by creating a nextjs application using $npx create-next-app@latest

2. once that finished, I went forward to installing shadcn using the command
$npx shadcn@latest init

but I got this error 

node:internal/modules/cjs/loader:1225
  const err = new Error(message);
              ^

Error: Cannot find module '@ts-morph/common'
Require stack:
- /home/tiam/.npm/_npx/d66c5096c7023bfb/node_modules/ts-morph/dist/ts-morph.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (/home/tiam/.npm/_npx/d66c5096c7023bfb/node_modules/ts-morph/dist/ts-morph.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tiam/.npm/_npx/d66c5096c7023bfb/node_modules/ts-morph/dist/ts-morph.js'
  ]
}

Node.js v22.14.0

even though when I ran the command $npx shadcn-ui@0.6.0 init, it worked fined 
I'm not comfortable with this aproach I would really love to always stay consistent with the documentation
please Is there something I need to fix ?

**Comment by anasselkadii** [comment]
i found the right solu 

Clear npx cache 
`npx clear-npx-cache`
 
then run 
`npx shadcn@latest init`
