### ISSUE TITLE
I am getting and error when installing shadcn components.  SyntaxError: Unexpected token '<', ")

### ISSUE THREAD

**Issue by kmasalam** [shadcn-ui/ui#2408]
npx shadcn-ui@latest add popover

SyntaxError: Unexpected token '<', ")
at Response.json (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/body.js:149:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4419
at async Promise.all (index 0)
at async N (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4386)
at async S (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:3644)
at async Command. (file:///home/abdus-salam/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:3:1986)

My components.json is like this

{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "",
    "cssVariables": false,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}

**Comment by MenaiAla** [comment]
Hi @kmasalam ,

Does this happen only with [popover](https://ui.shadcn.com/docs/components/popover) , or with any new component you want to install?

**Comment by kmasalam** [comment]
It was working fine for button and other few components, but suddenly the behaviour change, npx with any component not working.

![Screenshot from 2024-01-15 00-59-15](https://github.com/shadcn-ui/ui/assets/39186564/0a6561ad-8c1e-4556-908d-550ffa0d94f7)

**Comment by berenteb** [comment]
Same issue unfortunately, with multiple components!

**Comment by kmasalam** [comment]
@berenteb  Thank you.. man! now it's working... great relief. The error message was wrong for me..Its not giving me the write error message.

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by mastoj** [comment]
I experience this now. Added some components from v0 yesterday and it was working fine. Tried it today and it started failing. 

> npx shadcn@latest add "https://v0.dev/chat/b/braXqqa"

results with

> ⠸ Checking registry.
> 
> Something went wrong. Please check the error below for more details.
> If the problem persists, please open an issue on GitHub.
> 
> Unexpected token < in JSON at position 0

**Comment by mastoj** [comment]
I got it working using `shadcn@2.0.3`, but latest as of today didn't work. Not sure which version latest was pointing to.

**Comment by seppe-dalen** [comment]
Same here, can't add any components. Even with a new repository and fresh install of shadcn

**Comment by seppe-dalen** [comment]
@mastoj this seems to work `npx shadcn-ui@0.8.0 add button`

**Comment by mastoj** [comment]
@shadcn is already on it https://x.com/shadcn/status/1832342858545721554?s=46&t=nfYk5KqhPg_gTNv5Xtd1JQ

**Comment by shadcn** [comment]
I'm working on a fix for this. Please note that the new cli is `shadcn` (not `shadcn-ui`, which still works but will be deprecated).

Can you send me the url that you're installing from?

**Comment by mastoj** [comment]
@shadcn , one failing command that I have if you need it:

> npx shadcn@latest add "https://v0.dev/chat/b/braXqqa"

**Comment by boan-anbo** [comment]
> I experience this now. Added some components from v0 yesterday and it was working fine. Tried it today and it started failing.
> 
> > npx shadcn@latest add "https://v0.dev/chat/b/braXqqa"
> 
> results with
> 
> > ⠸ Checking registry.
> > Something went wrong. Please check the error below for more details.
> > If the problem persists, please open an issue on GitHub.
> > Unexpected token < in JSON at position 0

The chat works while the one on the front page doesn't.

This works: https://v0.dev/chat

**Comment by 1saifj** [comment]
same issues not resolved

**Comment by gertie-sheshe** [comment]
I get this error from manual installation of the button component

**Comment by Arden27** [comment]
had same thing.
Just switched from node 10 to 23
nvm use 23
;-)
