### ISSUE TITLE
Command: Commnd failed with exit code 1: npm install cmdk

### ISSUE THREAD

**Issue by MenaiAla** [shadcn-ui/ui#2509]
Hi everyone,

I started using Command component for the first time, however the installation fails each time I try to install this component.

## Requirements

1. pnpm
2. Node v-19.0.0

## Steps

`pnpm dlx shadcn-ui@latest add command`

## Expected 

Package installed

## Current

![image](https://github.com/shadcn-ui/ui/assets/20143684/24e1bbd0-ff33-421c-ad00-b6c6d6ba903b)

## Log

```

0 verbose cli /home/alaeddine/.nvm/versions/node/v19.0.0/bin/node /home/alaeddine/.nvm/versions/node/v19.0.0/bin/npm
1 info using npm@8.19.2
2 info using node@v19.0.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/alaeddine/Desktop/@credium/apps/web/.npmrc Completed in 3ms
10 timing config:load:project Completed in 11ms
11 timing config:load:file:/home/alaeddine/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/alaeddine/.nvm/versions/node/v19.0.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 3ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 34ms
19 timing npm:load:configload Completed in 35ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install cmdk
23 verbose argv "install" "cmdk"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 5ms
26 timing npm:load:display Completed in 7ms
27 verbose logfile logs-max:10 dir:/home/alaeddine/.npm/_logs
28 verbose logfile /home/alaeddine/.npm/_logs/2024-01-20T18_49_03_830Z-debug-0.log
29 timing npm:load:logFile Completed in 8ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 55ms
33 timing arborist:ctor Completed in 3ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing idealTree:init Completed in 90405ms
38 timing idealTree:userRequests Completed in 76ms
39 silly idealTree buildDeps
40 silly fetch manifest cmdk@^0.2.0
41 http fetch GET 200 https://registry.npmjs.org/cmdk 61ms (cache hit)
42 silly placeDep ROOT cmdk@0.2.0 REPLACE for: credium-gersthofen-app@0.1.0 want: ^0.2.0
43 silly fetch manifest @radix-ui/react-dialog@1.0.0
44 silly fetch manifest command-score@0.1.2
45 http fetch GET 200 https://registry.npmjs.org/command-score 21ms (cache hit)
46 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-dialog 30ms (cache hit)
47 timing idealTree:#root Completed in 284ms
48 silly placeDep node_modules/cmdk @radix-ui/react-dialog@1.0.0 OK for: cmdk@0.2.0 want: 1.0.0
49 silly placeDep ROOT command-score@0.1.2 OK for: cmdk@0.2.0 want: 0.1.2
50 silly fetch manifest @babel/runtime@^7.13.10
51 silly fetch manifest @radix-ui/primitive@1.0.0
52 silly fetch manifest @radix-ui/react-compose-refs@1.0.0
53 silly fetch manifest @radix-ui/react-context@1.0.0
54 silly fetch manifest @radix-ui/react-dismissable-layer@1.0.0
55 silly fetch manifest @radix-ui/react-focus-guards@1.0.0
56 silly fetch manifest @radix-ui/react-focus-scope@1.0.0
57 silly fetch manifest @radix-ui/react-id@1.0.0
58 silly fetch manifest @radix-ui/react-portal@1.0.0
59 silly fetch manifest @radix-ui/react-presence@1.0.0
60 silly fetch manifest @radix-ui/react-primitive@1.0.0
61 silly fetch manifest @radix-ui/react-slot@1.0.0
62 silly fetch manifest @radix-ui/react-use-controllable-state@1.0.0
63 silly fetch manifest aria-hidden@^1.1.1
64 silly fetch manifest react-remove-scroll@2.5.4
65 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2fprimitive 133ms (cache hit)
66 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-focus-scope 127ms (cache hit)
67 http fetch GET 200 https://registry.npmjs.org/@babel%2fruntime 148ms (cache hit)
68 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-id 136ms (cache hit)
69 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-compose-refs 154ms (cache hit)
70 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-dismissable-layer 152ms (cache hit)
71 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-presence 147ms (cache hit)
72 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-slot 148ms (cache hit)
73 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-use-controllable-state 155ms (cache hit)
74 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-context 179ms (cache hit)
75 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-focus-guards 178ms (cache hit)
76 http fetch GET 200 https://registry.npmjs.org/react-remove-scroll 163ms (cache hit)
77 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-primitive 175ms (cache hit)
78 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-portal 187ms (cache hit)
79 http fetch GET 200 https://registry.npmjs.org/aria-hidden 183ms (cache hit)
80 timing idealTree:node_modules/cmdk Completed in 258ms
81 timing idealTree:node_modules/command-score Completed in 0ms
82 silly placeDep ROOT @babel/runtime@7.23.8 OK for: @radix-ui/react-dialog@1.0.0 want: ^7.13.10
83 timing idealTree Completed in 91114ms
84 timing command:install Completed in 91145ms
85 verbose stack TypeError: Cannot read properties of null (reading 'matches')
85 verbose stack     at Link.matches (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1114:41)
85 verbose stack     at Link.canDedupe (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1068:15)
85 verbose stack     at PlaceDep.pruneDedupable (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:468:14)
85 verbose stack     at PlaceDep.placeInTree (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:329:14)
85 verbose stack     at PlaceDep.place (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:216:10)
85 verbose stack     at new PlaceDep (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
85 verbose stack     at /home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:31
85 verbose stack     at Array.map (<anonymous>)
85 verbose stack     at [buildDepStep] (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:8)
85 verbose stack     at async Arborist.buildIdealTree (/home/alaeddine/.nvm/versions/node/v19.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
86 verbose cwd /home/alaeddine/Desktop/@credium/apps/web
87 verbose Linux 5.15.0-56-generic
88 verbose node v19.0.0
89 verbose npm  v8.19.2
90 error Cannot read properties of null (reading 'matches')
91 verbose exit 1
92 timing npm Completed in 91422ms
93 verbose unfinished npm timer reify 1705776544101
94 verbose unfinished npm timer reify:loadTrees 1705776544120
95 verbose unfinished npm timer idealTree:buildDeps 1705776634607
96 verbose unfinished npm timer idealTree:node_modules/cmdk/node_modules/@radix-ui/react-dialog 1705776635153
97 verbose code 1
98 error A complete log of this run can be found in:
98 error     /home/alaeddine/.npm/_logs/2024-01-20T18_49_03_830Z-debug-0.log
```

**Comment by MenaiAla** [comment]
The issue happened because I used different node.js versions for the installation of the packages.
