### ISSUE TITLE
[Bug]: COMBOBOX - Uncaught TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by amirainfo** [shadcn-ui/ui#3047]
### Describe the bug

chunk-GSZ7ISAW.js?v=cacf6c60:16659 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at A (cmdk.js?v=cacf6c60:175:18)
    at U2 (cmdk.js?v=cacf6c60:141:13)
    at cmdk.js?v=cacf6c60:101:34
    at cmdk.js?v=cacf6c60:369:31
    at Map.forEach (<anonymous>)
    at cmdk.js?v=cacf6c60:369:15
    at commitHookEffectListMount (chunk-GSZ7ISAW.js?v=cacf6c60:16904:34)
    at commitLayoutEffectOnFiber (chunk-GSZ7ISAW.js?v=cacf6c60:16992:23)
    at commitLayoutMountEffects_complete (chunk-GSZ7ISAW.js?v=cacf6c60:17976:17)
    at commitLayoutEffects_begin (chunk-GSZ7ISAW.js?v=cacf6c60:17965:15)
    at commitLayoutEffects (chunk-GSZ7ISAW.js?v=cacf6c60:17916:11)
    at commitRootImpl (chunk-GSZ7ISAW.js?v=cacf6c60:19349:13)
    at commitRoot (chunk-GSZ7ISAW.js?v=cacf6c60:19273:13)
    at performSyncWorkOnRoot (chunk-GSZ7ISAW.js?v=cacf6c60:18891:11)
    at flushSyncCallbacks (chunk-GSZ7ISAW.js?v=cacf6c60:9135:30)
    at chunk-GSZ7ISAW.js?v=cacf6c60:18623:21
A @ cmdk.js?v=cacf6c60:175
U2 @ cmdk.js?v=cacf6c60:141
(anonymous) @ cmdk.js?v=cacf6c60:101
(anonymous) @ cmdk.js?v=cacf6c60:369
(anonymous) @ cmdk.js?v=cacf6c60:369
commitHookEffectListMount @ chunk-GSZ7ISAW.js?v=cacf6c60:16904
commitLayoutEffectOnFiber @ chunk-GSZ7ISAW.js?v=cacf6c60:16992
commitLayoutMountEffects_complete @ chunk-GSZ7ISAW.js?v=cacf6c60:17976
commitLayoutEffects_begin @ chunk-GSZ7ISAW.js?v=cacf6c60:17965
commitLayoutEffects @ chunk-GSZ7ISAW.js?v=cacf6c60:17916
commitRootImpl @ chunk-GSZ7ISAW.js?v=cacf6c60:19349
commitRoot @ chunk-GSZ7ISAW.js?v=cacf6c60:19273
performSyncWorkOnRoot @ chunk-GSZ7ISAW.js?v=cacf6c60:18891
flushSyncCallbacks @ chunk-GSZ7ISAW.js?v=cacf6c60:9135
(anonymous) @ chunk-GSZ7ISAW.js?v=cacf6c60:18623
Show 15 more frames
Show less
chunk-GSZ7ISAW.js?v=cacf6c60:16659 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at A (cmdk.js?v=cacf6c60:175:18)
    at U2 (cmdk.js?v=cacf6c60:141:13)
    at cmdk.js?v=cacf6c60:101:34
    at cmdk.js?v=cacf6c60:369:31
    at Map.forEach (<anonymous>)
    at cmdk.js?v=cacf6c60:369:15
    at commitHookEffectListMount (chunk-GSZ7ISAW.js?v=cacf6c60:16904:34)
    at invokeLayoutEffectMountInDEV (chunk-GSZ7ISAW.js?v=cacf6c60:18295:19)
    at invokeEffectsInDev (chunk-GSZ7ISAW.js?v=cacf6c60:19697:19)
    at commitDoubleInvokeEffectsInDEV (chunk-GSZ7ISAW.js?v=cacf6c60:19680:13)
    at flushPassiveEffectsImpl (chunk-GSZ7ISAW.js?v=cacf6c60:19499:13)
    at flushPassiveEffects (chunk-GSZ7ISAW.js?v=cacf6c60:19443:22)
    at commitRootImpl (chunk-GSZ7ISAW.js?v=cacf6c60:19412:13)
    at commitRoot (chunk-GSZ7ISAW.js?v=cacf6c60:19273:13)
    at performSyncWorkOnRoot (chunk-GSZ7ISAW.js?v=cacf6c60:18891:11)
    at flushSyncCallbacks (chunk-GSZ7ISAW.js?v=cacf6c60:9135:30)
    at chunk-GSZ7ISAW.js?v=cacf6c60:18623:21
A @ cmdk.js?v=cacf6c60:175
U2 @ cmdk.js?v=cacf6c60:141
(anonymous) @ cmdk.js?v=cacf6c60:101
(anonymous) @ cmdk.js?v=cacf6c60:369
(anonymous) @ cmdk.js?v=cacf6c60:369
commitHookEffectListMount @ chunk-GSZ7ISAW.js?v=cacf6c60:16904
invokeLayoutEffectMountInDEV @ chunk-GSZ7ISAW.js?v=cacf6c60:18295
invokeEffectsInDev @ chunk-GSZ7ISAW.js?v=cacf6c60:19697
commitDoubleInvokeEffectsInDEV @ chunk-GSZ7ISAW.js?v=cacf6c60:19680
flushPassiveEffectsImpl @ chunk-GSZ7ISAW.js?v=cacf6c60:19499
flushPassiveEffects @ chunk-GSZ7ISAW.js?v=cacf6c60:19443
commitRootImpl @ chunk-GSZ7ISAW.js?v=cacf6c60:19412
commitRoot @ chunk-GSZ7ISAW.js?v=cacf6c60:19273
performSyncWorkOnRoot @ chunk-GSZ7ISAW.js?v=cacf6c60:18891
flushSyncCallbacks @ chunk-GSZ7ISAW.js?v=cacf6c60:9135
(anonymous) @ chunk-GSZ7ISAW.js?v=cacf6c60:18623
Show 16 more frames
Show less
2VM190:1 The above error occurred in the <ForwardRef> component:

    at http://localhost:5173/node_modules/.vite/deps/cmdk.js?v=cacf6c60:69:11
    at _c (http://localhost:5173/src/components/ui/command.tsx:22:3)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-FAC6GVGS.js?v=cacf6c60:40:13
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-775GQN3S.js?v=cacf6c60:55:15)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-3NRPEL2A.js?v=cacf6c60:1870:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-VSZELCBL.js?v=cacf6c60:56:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-VSZELCBL.js?v=cacf6c60:33:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-FAC6GVGS.js?v=cacf6c60:40:13
    at http://localhost:5173/node_modules/.vite/deps/chunk-SWKG6U6L.js?v=cacf6c60:58:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-VSZELCBL.js?v=cacf6c60:56:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-VSZELCBL.js?v=cacf6c60:33:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-FAC6GVGS.js?v=cacf6c60:40:13
    at http://localhost:5173/node_modules/.vite/deps/chunk-SWKG6U6L.js?v=cacf6c60:290:11
    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js?v=cacf6c60:247:11
    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js?v=cacf6c60:210:101
    at $921a889cee6df7e8$export$99c2b779aa4e8b8b (http://localhost:5173/node_modules/.vite/deps/chunk-MHVLYAYR.js?v=cacf6c60:27:11)
    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js?v=cacf6c60:155:106
    at http://localhost:5173/node_modules/.vite/deps/chunk-VSZELCBL.js?v=cacf6c60:56:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-VSZELCBL.js?v=cacf6c60:33:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-FAC6GVGS.js?v=cacf6c60:40:13
    at http://localhost:5173/node_modules/.vite/deps/chunk-SWKG6U6L.js?v=cacf6c60:545:11
    at $921a889cee6df7e8$export$99c2b779aa4e8b8b (http://localhost:5173/node_modules/.vite/deps/chunk-MHVLYAYR.js?v=cacf6c60:27:11)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-775GQN3S.js?v=cacf6c60:55:15)
    at $cb5cc270b50c6fcd$export$dd679ffb4362d2d4 (http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js?v=cacf6c60:138:11)
    at _c (http://localhost:5173/src/components/ui/popover.tsx:22:3)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-775GQN3S.js?v=cacf6c60:55:15)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-775GQN3S.js?v=cacf6c60:55:15)
    at $cf1ac5d9fe0e8206$export$badac9ada3a0bdf9 (http://localhost:5173/node_modules/.vite/deps/chunk-3NRPEL2A.js?v=cacf6c60:1839:11)
    at $cb5cc270b50c6fcd$export$5b6b19405a83ff9d (http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js?v=cacf6c60:52:11)
    at div
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-FAC6GVGS.js?v=cacf6c60:40:13
    at $921a889cee6df7e8$export$99c2b779aa4e8b8b (http://localhost:5173/node_modules/.vite/deps/chunk-MHVLYAYR.js?v=cacf6c60:27:11)
    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-tabs.js?v=cacf6c60:137:11
    at _c5 (http://localhost:5173/src/components/ui/tabs.tsx:41:3)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-FAC6GVGS.js?v=cacf6c60:40:13
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-775GQN3S.js?v=cacf6c60:55:15)
    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-tabs.js?v=cacf6c60:42:11
    at form
    at div
    at div
    at ClientesEdit (http://localhost:5173/src/pages/Cadastros/Clientes/Edit/index.tsx?t=1710795221067:69:7)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=cacf6c60:3537:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=cacf6c60:3972:5)
    at Router (http://localhost:5173/src/routes/index.tsx:27:32)
    at AuthProvider (http://localhost:5173/src/contexts/AuthContext.tsx:24:3)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=cacf6c60:3915:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=cacf6c60:4655:5)
    at ThemeProvider (http://localhost:5173/src/components/theme/theme-provider.tsx:24:3)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
eval @ VM190:1
overrideMethod @ console.js:213
logCapturedError @ chunk-GSZ7ISAW.js?v=cacf6c60:14036
update.callback @ chunk-GSZ7ISAW.js?v=cacf6c60:14056
callCallback @ chunk-GSZ7ISAW.js?v=cacf6c60:10511
commitUpdateQueue @ chunk-GSZ7ISAW.js?v=cacf6c60:10528
commitLayoutEffectOnFiber @ chunk-GSZ7ISAW.js?v=cacf6c60:17083
commitLayoutMountEffects_complete @ chunk-GSZ7ISAW.js?v=cacf6c60:17976
commitLayoutEffects_begin @ chunk-GSZ7ISAW.js?v=cacf6c60:17965
commitLayoutEffects @ chunk-GSZ7ISAW.js?v=cacf6c60:17916
commitRootImpl @ chunk-GSZ7ISAW.js?v=cacf6c60:19349
commitRoot @ chunk-GSZ7ISAW.js?v=cacf6c60:19273
performSyncWorkOnRoot @ chunk-GSZ7ISAW.js?v=cacf6c60:18891
flushSyncCallbacks @ chunk-GSZ7ISAW.js?v=cacf6c60:9135
(anonymous) @ chunk-GSZ7ISAW.js?v=cacf6c60:18623
Show 14 more frames
Show less
chunk-GSZ7ISAW.js?v=cacf6c60:9145 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at A (cmdk.js?v=cacf6c60:175:18)
    at U2 (cmdk.js?v=cacf6c60:141:13)
    at cmdk.js?v=cacf6c60:101:34
    at cmdk.js?v=cacf6c60:369:31
    at Map.forEach (<anonymous>)
    at cmdk.js?v=cacf6c60:369:15
    at commitHookEffectListMount (chunk-GSZ7ISAW.js?v=cacf6c60:16904:34)
    at commitLayoutEffectOnFiber (chunk-GSZ7ISAW.js?v=cacf6c60:16992:23)
    at commitLayoutMountEffects_complete (chunk-GSZ7ISAW.js?v=cacf6c60:17976:17)
    at commitLayoutEffects_begin (chunk-GSZ7ISAW.js?v=cacf6c60:17965:15)
    at commitLayoutEffects (chunk-GSZ7ISAW.js?v=cacf6c60:17916:11)
    at commitRootImpl (chunk-GSZ7ISAW.js?v=cacf6c60:19349:13)
    at commitRoot (chunk-GSZ7ISAW.js?v=cacf6c60:19273:13)
    at performSyncWorkOnRoot (chunk-GSZ7ISAW.js?v=cacf6c60:18891:11)
    at flushSyncCallbacks (chunk-GSZ7ISAW.js?v=cacf6c60:9135:30)
    at chunk-GSZ7ISAW.js?v=cacf6c60:18623:21

### Affected component/components

ComboBox

### How to reproduce

<Popover open={open} onOpenChange={setOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      role="combobox"
                      aria-expanded={open}
                      className="w-[200px] justify-between"
                    >
                      {value
                        ? frameworks.find((framework) => framework.value === value)?.label
                        : "Select framework..."}
                      <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[200px] p-0">
                    <Command>
                      <CommandInput placeholder="Search framework..." />
                      <CommandEmpty>No framework found.</CommandEmpty>
                      <CommandGroup>
                        {frameworks.map((framework) => (
                          <CommandItem
                            key={framework.value}
                            value={framework.value}
                            onSelect={(currentValue) => {
                              setValuef(currentValue === value ? "" : currentValue)
                              setOpen(false)
                            }}
                          >
                            <Check
                              className={cn(
                                "mr-2 h-4 w-4",
                                value === framework.value ? "opacity-100" : "opacity-0"
                              )}
                            />
                            {framework.label}
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </Command>
                  </PopoverContent>
                 </Popover>

### System Info

```bash
MacOsx, Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ScottyMaher** [comment]
The issue might be the same as what I experienced, just with different and more detailed error logs than what I got. Try my solution here: https://github.com/shadcn-ui/ui/issues/3051

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
