### ISSUE TITLE
[bug]: not install => FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by arashdeveloper1380** [shadcn-ui/ui#3430]
### Describe the bug

hi 

I want to install this package, but it gives me this error, please help me, thank you

PS C:\xampp\htdocs\daily\frontend> npx shadcn-ui@latest init
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (file:///C:/Users/35.BULUTTAKIN/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
Failed to fetch styles from registry.
PS C:\xampp\htdocs\daily\frontend> 

### Affected component/components

when insatll package

### How to reproduce

hi 

I want to install this package, but it gives me this error, please help me, thank you

PS C:\xampp\htdocs\daily\frontend> npx shadcn-ui@latest init
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (file:///C:/Users/35.BULUTTAKIN/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
Failed to fetch styles from registry.
PS C:\xampp\htdocs\daily\frontend> 

### System Info

```bash
crome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by goswamianshuman** [comment]
Hey, I have some suggestions as this does not look's like an error cz I was able to initialize and install shadcn.

here are the number of factor's that I think you can check for:
1. proper internet connection
2. the folder where you are initializing shadcn
3. check if you have already Initialized the next.js or the required framework where shadcn works. 

I hope this three factors can help you to install shadcn.

Thankyou ☺

**Comment by arashdeveloper1380** [comment]
> Hey, I have some suggestions as this does not look's like an error cz I was able to initialize and install shadcn.
> 
> here are the number of factor's that I think you can check for:
> 
> 1. proper internet connection
> 2. the folder where you are initializing shadcn
> 3. check if you have already Initialized the next.js or the required framework where shadcn works.
> 
> I hope this three factors can help you to install shadcn.
> 
> Thankyou ☺



> Hey, I have some suggestions as this does not look's like an error cz I was able to initialize and install shadcn.
> 
> here are the number of factor's that I think you can check for:
> 
> 1. proper internet connection
> 2. the folder where you are initializing shadcn
> 3. check if you have already Initialized the next.js or the required framework where shadcn works.
> 
> I hope this three factors can help you to install shadcn.
> 
> Thankyou ☺

Thank you very much for your time

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
