### ISSUE TITLE
[bug]: All CLI installations don't work anymore

### ISSUE THREAD

**Issue by Cedcomps** [shadcn-ui/ui#3531]
### Describe the bug

When submitting CLI command I have a failed message from JSON. 
I changed repository npm but nevertheless nothing changed.
I updated and installed also again npm btw

See below with a test for add all components : 
npx shadcn-ui@latest add 
? Which components would you like to add? › Space to select. A to toggle all. Enter to submit. 
◯   accordion
? Which components would you like to add? › Space to select. A to toggle all. Enter to submit. 
◉   accordion
✔ Which components would you like to add? › accordion, alert, alert-dialog, aspect-ratio, avatar, badge, breadcrumb, button, calendar, card, carousel, checkbox, collapsible, command, context-menu, dialog, drawer, dropdown-menu, form, hover-card, input, input-otp, label, menubar, navigation-menu, pagination, popover, progress, radio-group, resizable, scroll-area, select, separator, sheet, skeleton, slider, sonner, switch, table, tabs, textarea, toast, toggle, toggle-group, tooltip
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4471
    at async Promise.all (index 0)
    at async _ (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4438)
    at async z (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:3696)
    at async Command.<anonymous> (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:3:1986)
Failed to fetch base color from registry.

### Affected component/components

All CLI components

### How to reproduce

Just try to add a component and it returns this : npx shadcn-ui@latest add label

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4471
    at async Promise.all (index 0)
    at async _ (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:4438)
    at async z (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:2:3696)
    at async Command.<anonymous> (file:///Users/Cedric/.npm/_npx/125ee17d583c4e03/node_modules/shadcn-ui/dist/index.js:3:1986)
Failed to fetch base color from registry.

### Codesandbox/StackBlitz link

https://github.com/Cedcomps/credo-alerte.git

### System Info

```bash
Mac under Visual Studio Code
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Cedcomps** [comment]
I deleted nodes_modules folder and package-lock.json.
Then I did npm I, then npx shadcn-ui@latest init
Everything go back again for the CLI
