### ISSUE TITLE
[bug]: Cannot add components using the CLI because of failed certificate verification

### ISSUE THREAD

**Issue by jakub-sekula** [shadcn-ui/ui#3535]
### Describe the bug

I am trying to add the Tooltip component by running `npx shadcn-ui@latest add tooltip`, but the command fails with the following error message: 

```
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (file:///C:/Users/js/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  erroredSysCall: undefined
}
Failed to fetch components from registry.
```

It worked fine yesterday and nothing changed on my side, is it possible that some certificate has expired?

### Affected component/components

Tooltip

### How to reproduce

Run `npx shadcn-ui@latest add tooltip`

### Logs

```bash
FetchError: request to https://ui.shadcn.com/registry/index.json failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (file:///C:/Users/js/AppData/Local/npm-cache/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  erroredSysCall: undefined
}
Failed to fetch components from registry.
```
```


### System Info

```bash
Windows 10.0.19042 Build 19042
npm 8.19.3
node 18.13.0
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ruru-m07** [comment]
@jakub-sekula are you able to add those components like `button` `input` `card` etc... or same problem with all components add?

**Comment by Widdin** [comment]
@jakub-sekula Are you by any chance using ESET Antivirus?

https://forum.eset.com/topic/40702-eset-ssl-protection-produces-an-invalid-certificate-chain-for-nodejs-apps/

**Comment by jakub-sekula** [comment]
> @jakub-sekula Are you by any chance using ESET Antivirus?
> 
> 
> 
> https://forum.eset.com/topic/40702-eset-ssl-protection-produces-an-invalid-certificate-chain-for-nodejs-apps/

I am actually, it's being used on my company network. I think this may be it, I'll check in with the IT people this week and let you know if and how it's solved. But it does sound like this issue is external to shadcn though.

**Comment by renzonj** [comment]
If you have access to ESET settings, you can disable the HTTPS Traffic scanning.
Setup > Internet Protection > Web access protection (gear icon) > HTTP(S) traffic scanning > then turn off the HTTPS Traffic scanning

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
