### ISSUE TITLE
[bug]: Doc error - the examples in the `ComboBox` section do not work - they are missing the `CommandList` element

### ISSUE THREAD

**Issue by noam-honig** [shadcn-ui/ui#3637]
### Describe the bug

I've tried the code examples from https://ui.shadcn.com/docs/components/combobox and they didn't work.

I investigated and I think that the samples are missing a `CommandList` element 
```tsx
 <PopoverContent className="w-[200px] p-0">
        <Command>
          <CommandInput placeholder="Search framework..." />
          <CommandList> {/* <---- this is missing ---->*/}
          <CommandEmpty>No framework found.</CommandEmpty>
          <CommandGroup>
            {frameworks.map((framework) => (
              <CommandItem
                key={framework.value}
                value={framework.value}
                onSelect={(currentValue) => {
                  setValue(currentValue === value ? "" : currentValue)
                  setOpen(false)
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === framework.value ? "opacity-100" : "opacity-0"
                  )}
                />
                {framework.label}
              </CommandItem>
            ))}
          </CommandGroup>
         </CommandList> {/* <---- this is missing ---->*/}
        </Command>
      </PopoverContent>
```

Version:
    "cmdk": "^1.0.0",
    "lucide-react": "^0.373.0",

Here's the error I got:
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at A (index.mjs:1:3990)
    at U2 (index.mjs:1:3003)
    at index.mjs:1:1763
    at index.mjs:1:10381
    at Map.forEach (<anonymous>)
    at index.mjs:1:10370
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    
    

### Affected component/components

ComboBox

### How to reproduce

Create a fresh project based on the https://ui.shadcn.com/docs/installation/vite
Add the combo box to it
Click on the combo 
See the error

Or open:
https://stackblitz.com/github/noam-honig/shadcn-combobox-docs-bug
Click on the combo
See the error

### Codesandbox/StackBlitz link

https://stackblitz.com/github/noam-honig/shadcn-combobox-docs-bug

### Logs

```bash
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at A (index.mjs:1:3990)
    at U2 (index.mjs:1:3003)
    at index.mjs:1:1763
    at index.mjs:1:10381
    at Map.forEach (<anonymous>)
    at index.mjs:1:10370
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
```

### System Info

```bash
Windows, Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ynikitiuk** [comment]
The problem is that shadcn installs latest version of dependencies, and there was a recent [major release](https://github.com/pacocoursey/cmdk/releases/tag/v1.0.0) of cmdk

You also need to update classes for `CommandItem` from `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` to `data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`, otherwise all options are disabled

**Comment by shahzaib-ai** [comment]
I am experiencing the same issue, as of now, removing cmdk v1.0.0 and using cmdk v0.2.1 makes it work. I think it would be nice if shadcn installed dependencies for the version they tested with, that might solve issues like this from occuring again.

**Comment by waldothedeveloper** [comment]
Does anybody knows when this will be fixed in the docs?

**Comment by khanhhuy130295** [comment]
I had the same problem with the sample

**Comment by mrlexz** [comment]
i got the same issue

**Comment by KhoeLe** [comment]
Your solution is as follows:

Step 01:
  - Navigate to the file components/ui/command.tsx and update the classes for `CommandItem` from `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` to `data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`. This change ensures that all options are disabled.
  (Note: Referring to the comment from @ynikitiuk)

Step 02:
- In the ComboboxDemo component, add `CommandList `as the parent of `CommandGroup `to resolve the issues:
```js
        <Command>
          <CommandInput placeholder="Search framework..." />
          <CommandEmpty>No framework found.</CommandEmpty>
          <CommandList>
          <CommandGroup>
            {frameworks.map((framework) => (
              <CommandItem
                key={framework.value}
                value={framework.value}
                onSelect={(currentValue) => {
                  setValue(currentValue === value ? "" : currentValue)
                  setOpen(false)
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === framework.value ? "opacity-100" : "opacity-0"
                  )}
                />
                {framework.label}
              </CommandItem>
            ))}
          </CommandGroup>
          </CommandList>
        </Command>
```
This should resolve the issues.
![image](https://github.com/shadcn-ui/ui/assets/63848705/39b89ced-6ed9-47c1-a7f5-6d60c6b8a99c)

**Comment by sao-coding** [comment]
> Your solution is as follows:
> 
> Step 01:
> 
> * Navigate to the file components/ui/command.tsx and update the classes for `CommandItem` from `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` to `data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`. This change ensures that all options are disabled.
>   (Note: Referring to the comment from @ynikitiuk)
> 
> Step 02:
> 
> * In the ComboboxDemo component, add `CommandList `as the parent of `CommandGroup `to resolve the issues:
> 
> ```js
>         <Command>
>           <CommandInput placeholder="Search framework..." />
>           <CommandEmpty>No framework found.</CommandEmpty>
>           <CommandList>
>           <CommandGroup>
>             {frameworks.map((framework) => (
>               <CommandItem
>                 key={framework.value}
>                 value={framework.value}
>                 onSelect={(currentValue) => {
>                   setValue(currentValue === value ? "" : currentValue)
>                   setOpen(false)
>                 }}
>               >
>                 <Check
>                   className={cn(
>                     "mr-2 h-4 w-4",
>                     value === framework.value ? "opacity-100" : "opacity-0"
>                   )}
>                 />
>                 {framework.label}
>               </CommandItem>
>             ))}
>           </CommandGroup>
>           </CommandList>
>         </Command>
> ```
> 
> This should resolve the issues. ![image](https://private-user-images.githubusercontent.com/63848705/328377399-39b89ced-6ed9-47c1-a7f5-6d60c6b8a99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODg3OTAsIm5iZiI6MTcxNTA4ODQ5MCwicGF0aCI6Ii82Mzg0ODcwNS8zMjgzNzczOTktMzliODljZWQtNmVkOS00N2MxLWE3ZjUtNmQ2MGM2YjhhOTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzhiZTZmY2E5YzNmZjk0ZDk3MDVkMGMxYzZlNTZjM2ZjNmNlMWMzMTUyNzRjMTc3OTZiNTQwYWExOGQ0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NHV21apFP_B9vSrz9mkwCq14u274bPWGDAPM0kDx2SI)

I can run normally without changing the class name.

**Comment by luchillo17** [comment]
> Step 01:
> 
> * Navigate to the file components/ui/command.tsx and update the classes for `CommandItem` from `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` to `data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`. This change ensures that all options are disabled.
>   (Note: Referring to the comment from @ynikitiuk)

@KhoeLe I think step 1 is not necessary anymore, it's funny the disabled class thingy was fixed but not the `CommandList` requirement...

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by luchillo17** [comment]
I believe this is fixed, not sure if it was through the Tailwind v4 update...

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
