### ISSUE TITLE
[bug]: Landing page crashes when examples > forms > account >  language selection dropdown clicked.

### ISSUE THREAD

**Issue by manjushsh** [shadcn-ui/ui#4096]
### Describe the bug

UI breaks with following errors on https://ui.shadcn.com. Not issue with any components.
<img width="1512" alt="image" src="https://github.com/shadcn-ui/ui/assets/94426452/ab44a5d5-d53c-4afd-b4f1-ecc76f298ab1">

This happens due to `CommandItem` component

### Affected component/components

Dropdown/Select or `CommandItem`. 

Works fine when h2 or other element is used.
<img width="636" alt="image" src="https://github.com/shadcn-ui/ui/assets/94426452/b7590c60-7c1f-42a1-9b0b-92053426690d">

### How to reproduce

1. Go to https://ui.shadcn.com/
2. From examples section click the following:
<img width="1512" alt="image" src="https://github.com/shadcn-ui/ui/assets/94426452/713d1194-bd99-47e6-8899-fc6c57afa6e3">
3. Open console to see error as suggested:
<img width="1512" alt="image" src="https://github.com/shadcn-ui/ui/assets/94426452/b0f0677f-ace8-4f18-ae45-61157bb88d29">

### Logs

```bash
TypeError: items is undefined
    NextJS 12
97525-01e51dd4c392194a.js:1:5105
    NextJS 66
The resource at “https://ui.shadcn
```

#### On local:
```bash
react-dom.development.js:20702 Uncaught 
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at A (index.mjs:20:4277)
    at U (index.mjs:20:3290)
    at eval (index.mjs:20:2050)
    at eval (index.mjs:20:13055)
    at Map.forEach (<anonymous>)
    at eval (index.mjs:20:13044)
    at commitHookEffectListMount (
```

### System Info

```bash
Mozilla Firefox v 127.0.1 on Macbook M2
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Nem4** [comment]
Can confirm. 
This also happens with this Language select inside of [Components -> Form (docs)](https://ui.shadcn.com/docs/components/combobox)

![image](https://github.com/shadcn-ui/ui/assets/17114757/97f84989-97b7-49a2-9e52-35e2c55fb7fc)
![image](https://github.com/shadcn-ui/ui/assets/17114757/b38e9f82-6e47-40c3-b3f6-c95025e21fc5)

**Comment by manjushsh** [comment]
Thanks @Nem4. I have updated #4097 with fix for this as well

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
