### ISSUE TITLE
[bug]: Application error: a client-side exception has occurred on examples > playground page

### ISSUE THREAD

**Issue by ChetSocio** [shadcn-ui/ui#4102]
### Describe the bug

If we explore playground examples on this page : https://ui.shadcn.com/examples/playground and click on load a preset dropdown, we get to see this error 
![image](https://github.com/shadcn-ui/ui/assets/114129405/4df9a4fc-d302-4357-a4c3-532cb8366547)

### Affected component/components

Entire Webpage

### How to reproduce

1. Go to [https://ui.shadcn.com/examples/playground](https://ui.shadcn.com/examples/playground)
2. Click on Load a preset dropdown
3. And the error occurs. 

### Codesandbox/StackBlitz link

https://ui.shadcn.com/examples/playground

### Logs

```bash
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at O (69016-e46275a046c77977.js:1:8485)
    at M (69016-e46275a046c77977.js:1:7484)
    at 69016-e46275a046c77977.js:1:6256
    at 69016-e46275a046c77977.js:1:14852
    at Map.forEach (<anonymous>)
    at 69016-e46275a046c77977.js:1:14841
    at aI (eb2a38ac-8c1a930f3b668d8a.js:1:72883)
    at aU (eb2a38ac-8c1a930f3b668d8a.js:1:72943)
    at aV (eb2a38ac-8c1a930f3b668d8a.js:1:73382)
```

### System Info

```bash
Windows 10 & Chrome
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ChetSocio** [comment]
The bug is on main shadcn website so there is no link to repreduction provided.

**Comment by manjushsh** [comment]
Has been updated in #4097

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
