### ISSUE TITLE
[bug]: SyntaxError: Unexpected token '<' when running npx shadcn-ui add sheet

### ISSUE THREAD

**Issue by Pieter1821** [shadcn-ui/ui#4136]
### Describe the bug

When running the command `npx shadcn-ui@latest add sheet`, I encountered a `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`. This error occurs when the script tries to parse an HTML document as JSON.

### Affected component/components

sheet

### How to reproduce

1. Run the command `npx shadcn-ui@latest add sheet`.
2. Observe the error output.

### Expected behavior
The command should execute without errors and add the sheet component.

![Screenshot 2024-07-01 063939](https://github.com/shadcn-ui/ui/assets/106959309/bc1d6c3b-fa03-4258-a5ed-cc140faf6931)

### Desktop 
- OS: [ Windows 11]
- Node.js version: [v20.13.1]
- NPM version: [10.8.1]

### Additional context
The issue persists even after ensuring a clean environment and updating Node.js and npm. The error suggests that the command is trying to parse an HTML document as JSON.

### Error Output
```plaintext
$ npx shadcn-ui add sheet
Need to install the following packages:
shadcn-ui@0.8.0
Ok to proceed? (y) y

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (file:///C:/Users/pieter/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/pieter/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:2:4471
    at async Promise.all (index 0)
    at async _ (file:///C:/Users/pieter/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:2:4438)
    at async z (file:///C:/Users/pieter/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:2:3696)
    at async Command.<anonymous> (file:///C:/Users/pieter/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:3:1986)
Failed to fetch base color from registry.




### System Info

```bash
### Desktop 
- OS: [ Windows 11]
- Node.js version: [v20.13.1]
- NPM version: [10.8.1]
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by spencersablan** [comment]
FYI, I'm not able to reproduce on an M1 Mac running Sonoma. 😅

**Comment by fabiofreitasbr** [comment]
To me, don't work in M1 Macos Sequoia... Verify, please!!!
