### ISSUE TITLE
[bug]: Combining Deno2 with NEXT.js and shadcn is failing

### ISSUE THREAD

**Issue by Cyb3rFl3x** [shadcn-ui/ui#5348]
### Describe the bug

Currently, I am trying to run NEXT.js with Deno2 and shadcn. Everything is working till I want to start adding shadcn components in my project. 

- The issue is only coming up if I add a shadcn button in my page.tsx
- Webpack is installed
- Tested with a fresh project

I got following output after doing shadcn init and adding a button and start next.js with deno task dev: 

As an Error in Next.js 
```bash
Error: __webpack_modules__[moduleId] is not a function
This error happened while generating the page. Any console logs will be displayed in the terminal window.
__webpack_require__
file:/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js (33:42)
eval
/./lib/utils.ts, <anonymous>
Object.(rsc)/./lib/utils.ts
file:/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js (173:1)
```

In the CLI:
```bash
deno task dev
Task dev next dev
  ▲ Next.js 14.2.15
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 3.3s
 ○ Compiling /_not-found ...
 ✓ Compiled /_not-found in 7.1s (475 modules)
 GET /_next/static/webpack/5d24c43cbc296b0b.webpack.hot-update.json 404 in 7649ms
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ✓ Compiled in 765ms (239 modules)
 ○ Compiling / ...
 ✓ Compiled / in 1095ms (525 modules)
 ⨯ TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eval (./lib/utils.ts, <anonymous>:6:72)
    at Object.(rsc)/./lib/utils.ts (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js:173:1)
    at __webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eval (./components/ui/button.tsx, <anonymous>:12:68)
    at Object.(rsc)/./components/ui/button.tsx (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js:162:1)
    at __webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx, <anonymous>:8:79)
    at Object.(rsc)/./app/page.tsx (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js:151:1)
    at Function.__webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eventLoopTick (ext:core/01_core.js:214:9)
    at async Promise.all (index 0)
digest: "773026919"
...
...
...
 GET / 500 in 272ms
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 841ms (354 modules)
 GET /favicon.ico 200 in 1039ms
´´´

### Affected component/components

Run dev server

### How to reproduce

```bash
deno run -A npm:create-next-app@latest
cd demo
deno task dev    # Next.js started
deno install npm:shadcn@latest 
npx shadcn init
npx shadcn add button
# added component like in the next session
deno task dev # failed
```

code:
```js
import { Button } from "@/components/ui/button";

export default function Home() {
  return (
        <Button/>
  );
}
```

### Codesandbox/StackBlitz link

is not possible because its a startup issue and not a code issue

### Logs

```bash
deno task dev
Task dev next dev
  ▲ Next.js 14.2.15
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 3.3s
 ○ Compiling /_not-found ...
 ✓ Compiled /_not-found in 7.1s (475 modules)
 GET /_next/static/webpack/5d24c43cbc296b0b.webpack.hot-update.json 404 in 7649ms
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ✓ Compiled in 765ms (239 modules)
 ○ Compiling / ...
 ✓ Compiled / in 1095ms (525 modules)
 ⨯ TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eval (./lib/utils.ts, <anonymous>:6:72)
    at Object.(rsc)/./lib/utils.ts (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js:173:1)
    at __webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eval (./components/ui/button.tsx, <anonymous>:12:68)
    at Object.(rsc)/./components/ui/button.tsx (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js:162:1)
    at __webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx, <anonymous>:8:79)
    at Object.(rsc)/./app/page.tsx (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/app/page.js:151:1)
    at Function.__webpack_require__ (/Users/felix/Workspace/Stuff/denodemo/demo/.next/server/webpack-runtime.js:33:42)
    at eventLoopTick (ext:core/01_core.js:214:9)
    at async Promise.all (index 0)
digest: "773026919"
...
...
...
 GET / 500 in 272ms
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 841ms (354 modules)
 GET /favicon.ico 200 in 1039ms
```

### System Info

```bash
MacOS Sonoma, Firefox, ...
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by jeffspurlock** [comment]
Were you able to do the initial `npx shadcn@latest init` command? I'm having a similar problem with Deno2/next.js/shadcn but I can't even get this init command to run to install all of the dependencies.

**Comment by Cyb3rFl3x** [comment]
Yes. I already have initialized it and afterward I added some components. I only got the issues after starting dev server and render some components. See screenshot:

## Console
<img width="679" alt="grafik" src="https://github.com/user-attachments/assets/a4e2ac1d-986b-4d7f-8d7f-c041e18a327f">

## Webview:
<img width="978" alt="grafik" src="https://github.com/user-attachments/assets/8dd60fc2-390d-4b42-ae80-54cc5987edbc">

**Comment by hongkongkiwi** [comment]
Same problem here. Any fix?

**Comment by teddybee** [comment]
@jeffspurlock  I have run this command:
deno run -A shadcn@latest init
but it hasn`t populate the package.json with dependencies.

**Comment by Jeffmagma** [comment]
I also seem to have a problem with just `deno run -A shadcn@latest init`:

    deno-shadcn-tailwind3> deno run -A npm:shadcn@latest init
    ✔ Preflight checks.
    ✔ Verifying framework. Found Vite.
    ✔ Validating Tailwind CSS.
    ✔ Validating import alias.
    √ Which style would you like to use? » New York
    √ Which color would you like to use as the base color? » Neutral
    √ Would you like to use CSS variables for theming? ... no / yes
    ✔ Writing components.json.
    ✔ Checking registry.
    ✔ Updating tailwind.config.js
    ✔ Updating src\App.css
    ⠸ Installing dependencies.
    Something went wrong. Please check the error below for more details.
    If the problem persists, please open an issue on GitHub.
    
    Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority lucide-react clsx tailwind-merge
    npm error Cannot read properties of null (reading 'matches')

**Comment by GeauxWeisbeck4** [comment]
@Cyb3rFl3x I'm running into kind of a similar issue, except mine says there's an issue with `@radix-ui/react-slot`:

```bash
$ npx shadcn@latest add button
✔ Checking registry.
⠸ Installing dependencies.
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: deno add @radix-ui/react-slot
error: @radix-ui/react-slot is missing a prefix. Did you mean `deno add npm:@radix-ui/react-slot`? 
```

I am going to investigate further on these. Maybe there's a common issue here with both bugs.

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
