### ISSUE TITLE
[bug]: Error when trying to install popover component

### ISSUE THREAD

**Issue by nandercarmo-plank** [shadcn-ui/ui#5383]
### Describe the bug

I'm trying to install the popover component to be able to use the combobox component, but I'm having this error every time (I've already tried the manual and cli install modes, with the same result):

```shell
npx shadcn@latest add popover

npm error Cannot read properties of undefined (reading 'extraneous')
npm error A complete log of this run can be found in: /Users/nandercarmo/.npm/_logs/2024-10-14T20_16_29_814Z-debug-0.log
``` 

This is my package.json:

```json
"dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@mui/icons-material": "^5.15.14",
    "@mui/material": "^5.15.14",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-progress": "^1.0.3",
    "@radix-ui/react-select": "^2.1.2",
    "@radix-ui/react-slot": "^1.0.2",
    "@tanstack/react-query": "^5.20.5",
    "@tanstack/react-table": "^8.12.0",
    "@types/react-router": "5.1.20",
    "axios": "^1.6.7",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "cmdk": "^1.0.0",
    "dotenv": "^16.4.5",
    "flowbite": "^2.3.0",
    "lucide-react": "^0.331.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-query": "^3.39.3",
    "react-retool": "^1.4.0",
    "react-router-dom": "6.22.1",
    "react-toastify": "^10.0.5",
    "react-top-loading-bar": "^2.3.1",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "vite-plugin-svgr": "^4.2.0",
    "zustand": "^4.5.0"
  },
 ```
 
 I didn't find any solution for this and I've already tried to:
 
 ```shell
 rm -rf node_modules package-lock.json && npm cache clean --force
 ```
 
 And nothing worked!
 
 PS: I'm using node `v22.9.0` and npm `10.8.3`

### Affected component/components

Combobox, Popover

### How to reproduce

Just try to run the following command: 

```shell
npx shadcn@latest add popover
```

### Logs

```bash
0 verbose cli /Users/nandercarmo/.nvm/versions/node/v22.9.0/bin/node /Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.8.3
2 info using node@v22.9.0
3 silly config load:file:/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/npmrc
4 info config found workspace root at /Users/nandercarmo/Nander/Github/plank/panel/backup/panel-monorepo
5 silly config load:file:/Users/nandercarmo/Nander/Github/plank/panel/backup/panel-monorepo/.npmrc
6 silly config load:file:/Users/nandercarmo/.npmrc
7 silly config load:file:/Users/nandercarmo/.nvm/versions/node/v22.9.0/etc/npmrc
8 verbose title npm exec shadcn@latest add popover
9 verbose argv "exec" "--" "shadcn@latest" "add" "popover"
10 verbose logfile logs-max:10 dir:/Users/nandercarmo/.npm/_logs/2024-10-14T20_16_29_814Z-
11 verbose logfile /Users/nandercarmo/.npm/_logs/2024-10-14T20_16_29_814Z-debug-0.log
12 warn using --force Recommended protections disabled.
13 silly logfile start cleaning logs, removing 1 files
14 silly logfile done cleaning log files
15 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
16 verbose stack TypeError: Cannot read properties of undefined (reading 'extraneous')
16 verbose stack     at #loadLink (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:296:30)
16 verbose stack     at #resolveLinks (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:203:34)
16 verbose stack     at #loadFromShrinkwrap (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:91:29)
16 verbose stack     at Arborist.loadVirtual (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:41:37)
16 verbose stack     at #loadActual (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:153:59)
16 verbose stack     at async exec (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:175:21)
16 verbose stack     at async Exec.execWorkspaces (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/lib/commands/exec.js:37:7)
16 verbose stack     at async Npm.exec (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/lib/npm.js:207:9)
16 verbose stack     at async module.exports (/Users/nandercarmo/.nvm/versions/node/v22.9.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
17 error Cannot read properties of undefined (reading 'extraneous')
18 verbose cwd /Users/nandercarmo/Nander/Github/plank/panel/backup/panel-monorepo/apps/advertiser
19 verbose os Darwin 23.5.0
20 verbose node v22.9.0
21 verbose npm  v10.8.3
22 verbose exit 1
23 verbose code 1
24 error A complete log of this run can be found in: /Users/nandercarmo/.npm/_logs/2024-10-14T20_16_29_814Z-debug-0.log
```

### System Info

```bash
Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: Mac14,2
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.121.1
      Activation Lock Status: Enabled

Browser: Chromium
Node: v22.9.0
NPM: 10.8.3
React app with vite
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shubhamsharma024** [comment]
Had the same issue, just degraded the node to v20 and it works.....
