### ISSUE TITLE
[bug]: `TabsTrigger` must be used within `Tabs`

### ISSUE THREAD

**Issue by StupidRepo** [shadcn-ui/ui#5537]
### Describe the bug

When I use this code snippet from the docs, I get the following error:
```
		<Tabs defaultValue="account">
			<TabsList>
			  <TabsTrigger value="account">Account</TabsTrigger>
			  <TabsTrigger value="password">Password</TabsTrigger>
			</TabsList>
			<TabsContent value="account">Make changes to your account here.</TabsContent>
			<TabsContent value="password">Change your password here.</TabsContent>
		</Tabs>
```

### Affected component/components

Tabs, TabsTrigger

### How to reproduce

1.  Setup astro with shadcn
2. Use the provided code snippet
3. Hopefully encounter the error.

### Codesandbox/StackBlitz link

I can't figure out how to pop open a terminal to install shadcn in these 2 apps...

### Logs

```bash
Error: `TabsTrigger` must be used within `Tabs`
    at useContext2 (file:///Users/brad/CCClient/node_modules/@radix-ui/react-context/dist/index.mjs:38:13)
    at file:///Users/brad/CCClient/node_modules/@radix-ui/react-tabs/dist/index.mjs:95:21
    at renderWithHooks (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
    at renderForwardRef (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:5919:18)
    at renderElement (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderForwardRef (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:5936:5)
    at renderElement (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (/Users/brad/CCClient/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
```

### System Info

```bash
macOS 14
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by StupidRepo** [comment]
It seems like it does this for HoverCardContent too?

**Comment by jpmaga** [comment]
Are you trying to use this in an astro template? If so, I think this might have to do with the way astro handles children components. You can try to extract this whole thing to its own react component and then load that in astro, or try to enable the experimental react children flag.

**Comment by StupidRepo** [comment]
Ah yeah I figured that out. I do have to put it in a seperate component. Thank you!
