### ISSUE TITLE
[bug]: ToggleGroupItem does not recognize that it's within a ToggleGroup in Astro

### ISSUE THREAD

**Issue by Glitched** [shadcn-ui/ui#5598]
### Describe the bug

I get a runtime error that `ToggleGroupItem` must be used within `ToggleGroup` even though all ToggleGroupItem are within a ToggleGroup

```
Error: `ToggleGroupItem` must be used within `ToggleGroup`
    at useContext2 (file:///path/to/my/project/node_modules/@radix-ui/react-context/dist/index.mjs:37:13)
    at file:///path/to/my/project/node_modules/@radix-ui/react-toggle-group/dist/index.mjs:122:26
    at renderWithHooks (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
    at renderForwardRef (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:5919:18)
    at renderElement (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderForwardRef (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:5936:5)
    at renderElement (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (/path/to/my/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
```

### Affected component/components

ToggleGroup, ToggleGroupItem

### How to reproduce

1. Start a new astro project (I set my typescript settings to strictest, but I don't think that should matter)
2. Add Shadcn following the [docs for astro](https://ui.shadcn.com/docs/installation/astro)
3. Add the toggle group with `npx shadcn@latest add toggle-group`
4. Everything should still work at this step if you run the dev server
5. Paste the example code in Layout.astro
```jsx
<ToggleGroup type="single">
  <ToggleGroupItem value="a">A</ToggleGroupItem>
  <ToggleGroupItem value="b">B</ToggleGroupItem>
  <ToggleGroupItem value="c">C</ToggleGroupItem>
</ToggleGroup>
```

7. Observe the error `Error: `ToggleGroupItem` must be used within `ToggleGroup`

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/github-ezhys2?file=src%2Fpages%2Findex.astro

### System Info

```bash
Irrelevant
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Glitched** [comment]
Closing as a dupe of the resolved issue https://github.com/shadcn-ui/ui/discussions/1509
