### ISSUE TITLE
[bug]: Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge

### ISSUE THREAD

**Issue by Programmer118** [shadcn-ui/ui#5604]
### Describe the bug

# npm resolution error report

While resolving: notion-clone@0.1.0
Found: react@19.0.0-rc-69d4b800-20241021
node_modules/react
  react@"19.0.0-rc-69d4b800-20241021" from the root project

Could not resolve dependency:
peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
node_modules/@radix-ui/react-icons
  @radix-ui/react-icons@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

### Affected component/components

?

### How to reproduce

1

### Logs

```bash
0 verbose cli E:\NodeJs\node.exe C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.2
2 info using node@v22.2.0
3 silly config load:file:C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\npmrc
4 silly config load:file:E:\project\next-project\notion-clone\.npmrc
5 silly config load:file:C:\Users\Anupam\.npmrc
6 silly config load:file:C:\Users\Anupam\AppData\Roaming\npm\etc\npmrc
7 verbose title npm install tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge
8 verbose argv "install" "tailwindcss-animate" "class-variance-authority" "lucide-react" "@radix-ui/react-icons" "clsx" "tailwind-merge"
9 verbose logfile logs-max:10 dir:C:\Users\Anupam\AppData\Local\npm-cache\_logs\2024-10-28T10_47_51_645Z-
10 verbose logfile C:\Users\Anupam\AppData\Local\npm-cache\_logs\2024-10-28T10_47_51_645Z-debug-0.log
11 silly packumentCache heap:2127822848 maxSize:531955712 maxEntrySize:265977856
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest tailwindcss-animate@*
16 silly packumentCache full:https://registry.npmjs.org/tailwindcss-animate cache-miss
17 http fetch GET 200 https://registry.npmjs.org/tailwindcss-animate 231ms (cache hit)
18 silly packumentCache full:https://registry.npmjs.org/tailwindcss-animate set size:29893 disposed:false
19 silly fetch manifest tailwindcss@^3.4.1
20 silly packumentCache full:https://registry.npmjs.org/tailwindcss cache-miss
21 http fetch GET 200 https://registry.npmjs.org/tailwindcss 58ms (cache hit)
22 silly packumentCache full:https://registry.npmjs.org/tailwindcss set size:7703891 disposed:false
23 silly fetch manifest class-variance-authority@*
24 silly packumentCache full:https://registry.npmjs.org/class-variance-authority cache-miss
25 http fetch GET 200 https://registry.npmjs.org/class-variance-authority 11ms (cache hit)
26 silly packumentCache full:https://registry.npmjs.org/class-variance-authority set size:147580 disposed:false
27 silly fetch manifest lucide-react@*
28 silly packumentCache full:https://registry.npmjs.org/lucide-react cache-miss
29 http fetch GET 200 https://registry.npmjs.org/lucide-react 21ms (cache hit)
30 silly packumentCache full:https://registry.npmjs.org/lucide-react set size:1779655 disposed:false
31 silly fetch manifest react@19.0.0-rc-69d4b800-20241021
32 silly packumentCache full:https://registry.npmjs.org/react cache-miss
33 http fetch GET 200 https://registry.npmjs.org/react 76ms (cache hit)
34 silly packumentCache full:https://registry.npmjs.org/react set size:5095896 disposed:false
35 silly fetch manifest @radix-ui/react-icons@*
36 silly packumentCache full:https://registry.npmjs.org/@radix-ui%2freact-icons cache-miss
37 http fetch GET 200 https://registry.npmjs.org/@radix-ui%2freact-icons 12ms (cache hit)
38 silly packumentCache full:https://registry.npmjs.org/@radix-ui%2freact-icons set size:25990 disposed:false
39 silly fetch manifest react@^16.x || ^17.x || ^18.x
40 silly packumentCache full:https://registry.npmjs.org/react cache-miss
41 http fetch GET 200 https://registry.npmjs.org/react 34ms (cache hit)
42 silly packumentCache full:https://registry.npmjs.org/react set size:5095896 disposed:false
43 verbose stack Error: unable to resolve dependency tree
43 verbose stack     at #failPeerConflict (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1360:25)
43 verbose stack     at #loadPeerSet (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1326:33)
43 verbose stack     at async #buildDepStep (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:901:11)
43 verbose stack     at async Arborist.buildIdealTree (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:181:7)
43 verbose stack     at async Promise.all (index 1)
43 verbose stack     at async Arborist.reify (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:131:5)
43 verbose stack     at async Install.exec (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:150:5)
43 verbose stack     at async Npm.exec (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\lib\npm.js:207:9)
43 verbose stack     at async module.exports (C:\Users\Anupam\AppData\Roaming\npm\node_modules\npm\lib\cli\entry.js:74:5)
44 error code ERESOLVE
45 error ERESOLVE unable to resolve dependency tree
46 error
47 error While resolving: notion-clone@0.1.0
47 error Found: react@19.0.0-rc-69d4b800-20241021
47 error node_modules/react
47 error   react@"19.0.0-rc-69d4b800-20241021" from the root project
47 error
47 error Could not resolve dependency:
47 error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
47 error node_modules/@radix-ui/react-icons
47 error   @radix-ui/react-icons@"*" from the root project
47 error
47 error Fix the upstream dependency conflict, or retry
47 error this command with --force or --legacy-peer-deps
47 error to accept an incorrect (and potentially broken) dependency resolution.
48 error
48 error
48 error For a full report see:
48 error C:\Users\Anupam\AppData\Local\npm-cache\_logs\2024-10-28T10_47_51_645Z-eresolve-report.txt
49 silly unfinished npm timer reify 1730112473695
50 silly unfinished npm timer reify:loadTrees 1730112473706
51 silly unfinished npm timer idealTree:buildDeps 1730112474102
52 silly unfinished npm timer idealTree:#root 1730112474104
53 verbose cwd E:\project\next-project\notion-clone
54 verbose os Windows_NT 10.0.19045
55 verbose node v22.2.0
56 verbose npm  v10.8.2
57 verbose exit 1
58 verbose code 1
59 error A complete log of this run can be found in: C:\Users\Anupam\AppData\Local\npm-cache\_logs\2024-10-28T10_47_51_645Z-debug-0.log
```

### System Info

```bash
Host Name:                 UNKNOWN
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          lenovo
Registered Organization:   
Product ID:                00327-35146-09365-AAOEM
Original Install Date:     11/16/2021, 8:52:07 PM
System Boot Time:          10/25/2024, 7:37:20 PM
System Manufacturer:       LENOVO
System Model:              81H7
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 9 GenuineIntel ~2300 Mhz
BIOS Version:              LENOVO 8QCN21WW(V1.09), 12/30/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              00004009
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     3,962 MB
Available Physical Memory: 575 MB
Virtual Memory: Max Size:  13,271 MB
Virtual Memory: Available: 5,645 MB
Virtual Memory: In Use:    7,626 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\UNKNOWN
Hotfix(s):                 30 Hotfix(s) Installed.
                           [01]: KB5036618
                           [02]: KB5031988
                           [03]: KB4562830
                           [04]: KB5003791
                           [05]: KB5011048
                           [06]: KB5012170
                           [07]: KB5015684
                           [08]: KB5040427
                           [09]: KB5006753
                           [10]: KB5007273
                           [11]: KB5011352
                           [12]: KB5014032
                           [13]: KB5014035
                           [14]: KB5014671
                           [15]: KB5015895
                           [16]: KB5016705
                           [17]: KB5018506
                           [18]: KB5020372
                           [19]: KB5022924
                           [20]: KB5025315
                           [21]: KB5026879
                           [22]: KB5028380
                           [23]: KB5029709
                           [24]: KB5032392
                           [25]: KB5032907
                           [26]: KB5037018
                           [27]: KB5037240
                           [28]: KB5037995
                           [29]: KB5039336
                           [30]: KB5043130
Network Card(s):           4 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [02]: Realtek 8821CE Wireless LAN 802.11ac PCI-E NIC
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.7
                                 [02]: fe80::bff5:8675:4f33:7cc0
                           [03]: Realtek PCIe FE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [04]: Microsoft Wi-Fi Direct Virtual Adapter
                                 Connection Name: Local Area Connection* 16
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 169.254.247.234
                                 [02]: fe80::ae74:3cc7:1364:628
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be 
displayed.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
I'm working on a fix. Let's use https://github.com/shadcn-ui/ui/issues/5557 to track since they are related.

**Comment by saurabh0829** [comment]
Command failed with ENOENT: yarn add tailwindcss-animate class-variance-authority lucide-react clsx tailwind-merge
spawn yarn ENOENT

Im using bun to install shadcn and getting this error again and again.

**Comment by IkkeLucky** [comment]
months went by and this bug still cant be resolved? really what the hell are they doing?

**Comment by shahul01** [comment]
Follow this
https://github.com/pnpm/pnpm/issues/7738#issuecomment-1982910416
