### ISSUE TITLE
[bug]: running npx shadcn@latest init the modifications to tailwind.config.ts generate an error 

### ISSUE THREAD

**Issue by ArcosAdrian** [shadcn-ui/ui#6035]
### Describe the bug

When running npx shadcn@latest init the modifications to tailwind.config.ts generate an error by backgroundImage: {
  			video: 'url('../images/video/video.png')'
  		}, it is incorrectly configured, it should be backgroundImage: {
  			video: 'url("../images/video/video.png")'
  		},

### Affected component/components

none

### How to reproduce

create netx app run
npx shadcn@latest init

![Next Error](https://github.com/user-attachments/assets/814126a4-a7f7-4d38-aaec-c8ef8fabf905)

### Logs

```bash
:3000/:1 
        
        
        GET http://localhost:3000/ 500 (Internal Server Error)
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again
index.tsx:935  Uncaught ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js):
SyntaxError: Unexpected token, expected "," (311:44)
    at unexpected (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\util.js:99:15)
    at expect (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\util.js:86:5)
    at parseObj (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:759:20)
    at parseExprAtom (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:553:7)
    at parseExprSubscripts (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:276:20)
    at parseMaybeUnary (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:257:20)
    at parseExprOps (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:185:20)
    at parseMaybeConditional (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:157:20)
    at baseParseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:142:20)
    at tsParseMaybeAssignWithoutJSX (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\plugins\typescript.js:1580:45)
    at tsParseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\plugins\typescript.js:1548:12)
    at parseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:121:43)
    at parseObjectProperty (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:851:7)
    at parseObjPropValue (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:892:5)
    at parseObj (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:808:5)
    at parseExprAtom (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:553:7)
    at parseExprSubscripts (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:276:20)
    at parseMaybeUnary (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:257:20)
    at parseExprOps (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:185:20)
    at parseMaybeConditional (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:157:20)
    at baseParseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:142:20)
    at tsParseMaybeAssignWithoutJSX (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\plugins\typescript.js:1580:45)
    at tsParseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\plugins\typescript.js:1548:12)
    at parseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:121:43)
    at parseObjectProperty (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:851:7)
    at parseObjPropValue (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:892:5)
    at parseObj (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:808:5)
    at parseExprAtom (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:553:7)
    at parseExprSubscripts (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:276:20)
    at parseMaybeUnary (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:257:20)
    at parseExprOps (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:185:20)
    at parseMaybeConditional (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:157:20)
    at baseParseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:142:20)
    at tsParseMaybeAssignWithoutJSX (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\plugins\typescript.js:1580:45)
    at tsParseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\plugins\typescript.js:1548:12)
    at parseMaybeAssign (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:121:43)
    at parseObjectProperty (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:851:7)
    at parseObjPropValue (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\parser\traverser\expression.js:892:5)
    at parseObj (F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\sucrase\dist\pars
getServerError @ nodeStackFrames.ts:30
eval @ index.tsx:935
setTimeout
hydrate @ index.tsx:922
await in hydrate
pageBootrap @ page-bootstrap.ts:22
eval @ next-dev.ts:21
Promise.then
eval @ next-dev.ts:20
./node_modules/next/dist/client/next-dev.js @ main.js:820
options.factory @ webpack.js:647
__webpack_require__ @ webpack.js:37
__webpack_exec__ @ main.js:1964
(anonymous) @ main.js:1965
webpackJsonpCallback @ webpack.js:1195
(anonymous) @ main.js:9
websocket.ts:27 [HMR] connected
hydration-error-info.ts:72  ./node_modules/flatpickr/dist/flatpickr.min.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[3]!./node_modules/flatpickr/dist/flatpickr.min.css
SyntaxError: Unexpected token, expected "," (311:44)
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./node_modules/jsvectormap/dist/jsvectormap.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[3]!./node_modules/jsvectormap/dist/jsvectormap.css
SyntaxError: Unexpected token, expected "," (311:44)
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./src/css/satoshi.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[3]!./src/css/satoshi.css
SyntaxError: Unexpected token, expected "," (311:44)
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./src/css/style.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[3]!./src/css/style.css
SyntaxError: Unexpected token, expected "," (311:44)
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./node_modules/flatpickr/dist/flatpickr.min.css
SyntaxError: Unexpected token, expected "," (311:44)
-- inner error --
SyntaxError: Unexpected token, expected "," (311:44)
Generated code for F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[2]!F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[3]!F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\flatpickr\dist\flatpickr.min.css
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./node_modules/jsvectormap/dist/jsvectormap.css
SyntaxError: Unexpected token, expected "," (311:44)
-- inner error --
SyntaxError: Unexpected token, expected "," (311:44)
Generated code for F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[2]!F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[3]!F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\jsvectormap\dist\jsvectormap.css
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./src/css/satoshi.css
SyntaxError: Unexpected token, expected "," (311:44)
-- inner error --
SyntaxError: Unexpected token, expected "," (311:44)
Generated code for F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[2]!F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[3]!F:\TRABAJO\GAMO\aas\gamo-dashboard\src\css\satoshi.css
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
hydration-error-info.ts:72  ./src/css/style.css
SyntaxError: Unexpected token, expected "," (311:44)
-- inner error --
SyntaxError: Unexpected token, expected "," (311:44)
Generated code for F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[2]!F:\TRABAJO\GAMO\aas\gamo-dashboard\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[14].oneOf[12].use[3]!F:\TRABAJO\GAMO\aas\gamo-dashboard\src\css\style.css
overrideMethod @ hook.js:608
console.error @ hydration-error-info.ts:72
window.console.error @ setup-hydration-warning.ts:21
handleErrors @ hot-reloader-client.ts:199
processMessage @ hot-reloader-client.ts:295
eval @ hot-reloader-client.ts:82
handleMessage @ websocket.ts:34
```

### System Info

```bash
windows 11
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ArcosAdrian** [comment]
![image](https://github.com/user-attachments/assets/267ddfb4-3302-4a63-8af3-a42085cf6dd7)

**Comment by shadcn** [comment]
This issue has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

**Comment by shadcn** [comment]
This issue has been automatically closed due to one year of inactivity. If you’re still experiencing a similar problem or have additional details to share, please open a new issue following our current issue template. Your updated report helps us investigate and address concerns more efficiently. Thank you for your understanding! (This is an automated message)
